import type {
  ClusterDetailPayload,
  FleetPayload,
  NextCheckPlanCandidate,
  NotificationsPayload,
  ProposalsPayload,
  RunPayload,
} from "../types";

export const sampleNextCheckCandidates: NextCheckPlanCandidate[] = [
  {
    description: "Collect kubelet logs for control-plane pods",
    targetCluster: "cluster-a",
    sourceReason: "warning_event_threshold",
    expectedSignal: "logs",
    suggestedCommandFamily: "kubectl-logs",
    safeToAutomate: true,
    requiresOperatorApproval: false,
    riskLevel: "low",
    estimatedCost: "low",
    confidence: "high",
    priorityLabel: "primary",
    gatingReason: null,
    duplicateOfExistingEvidence: false,
    duplicateEvidenceDescription: null,
    candidateId: "candidate-logs",
    candidateIndex: 0,
    approvalStatus: "not-required",
    approvalState: "not-required",
    executionState: "executed-success",
    outcomeStatus: "executed-success",
    latestArtifactPath: "/artifacts/run-123-next-check-execution-0.json",
    latestTimestamp: "2026-04-06T12:05:00Z",
    normalizationReason: "selection_label",
    safetyReason: "known_command",
    approvalReason: null,
    duplicateReason: null,
    blockingReason: null,
    targetContext: "cluster-a · control-plane pods",
    commandPreview: "kubectl logs deployment/control-plane --context cluster-a",
  },
  {
    description: "Describe diag CRD for control plane",
    targetCluster: null,
    sourceReason: "diag-availability",
    expectedSignal: "events",
    suggestedCommandFamily: "kubectl-describe",
    safeToAutomate: false,
    requiresOperatorApproval: true,
    riskLevel: "medium",
    estimatedCost: "medium",
    confidence: "medium",
    priorityLabel: "secondary",
    gatingReason: "Command not recognized or too vague",
    duplicateOfExistingEvidence: false,
    duplicateEvidenceDescription: null,
    candidateId: "candidate-describe",
    candidateIndex: 1,
    approvalStatus: "approval-required",
    approvalState: "approval-required",
    executionState: "unexecuted",
    outcomeStatus: "approval-required",
    latestArtifactPath: null,
    latestTimestamp: null,
    normalizationReason: "selection_default",
    safetyReason: "unknown_command",
    approvalReason: "unknown_command",
    duplicateReason: null,
    blockingReason: "unknown_command",
    targetContext: "cluster-b · diag CRD",
    commandPreview: "kubectl describe diag customresourcedefinition --context cluster-b",
  },
  {
    description: "Capture kubelet metrics for control-plane nodes",
    targetCluster: "cluster-a",
    sourceReason: "metric-surge",
    expectedSignal: "metrics",
    suggestedCommandFamily: "kubectl-get",
    safeToAutomate: false,
    requiresOperatorApproval: true,
    riskLevel: "medium",
    estimatedCost: "medium",
    confidence: "low",
    priorityLabel: "fallback",
    gatingReason: "Matches deterministic next check: Collect kubelet metrics",
    duplicateOfExistingEvidence: true,
    duplicateEvidenceDescription: "Collect kubelet metrics",
    candidateId: "candidate-metrics",
    candidateIndex: 2,
    approvalStatus: "not-required",
    approvalState: "not-required",
    executionState: "unexecuted",
    outcomeStatus: "not-used",
    latestArtifactPath: null,
    latestTimestamp: null,
    normalizationReason: "selection_default",
    safetyReason: "duplicate_evidence",
    approvalReason: "duplicate_evidence",
    duplicateReason: "exact_match",
    blockingReason: "duplicate",
    targetContext: "cluster-a · nodes",
    commandPreview: "kubectl get nodes --context cluster-a",
  },
];

export const sampleRun: RunPayload = {
  runId: "run-123",
  label: "Daily sweep",
  timestamp: "2026-04-06T12:00:00Z",
  collectorVersion: "collector:v1.2.0",
  clusterCount: 2,
  drilldownCount: 5,
  proposalCount: 4,
  externalAnalysisCount: 1,
  notificationCount: 2,
  artifacts: [
    { label: "run manifest", path: "/artifacts/run-manifest.json" },
  ],
  runStats: {
    lastRunDurationSeconds: 32,
    totalRuns: 12,
    p50RunDurationSeconds: 24,
    p95RunDurationSeconds: 48,
    p99RunDurationSeconds: 64,
  },
  llmStats: {
    totalCalls: 3,
    successfulCalls: 2,
    failedCalls: 1,
    lastCallTimestamp: "2026-04-06T11:59:00Z",
    p50LatencyMs: 110,
    p95LatencyMs: 220,
    p99LatencyMs: 300,
    providerBreakdown: [
      { provider: "k8sgpt", calls: 2, failedCalls: 0 },
      { provider: "default", calls: 1, failedCalls: 1 },
    ],
    scope: "current_run",
  },
  historicalLlmStats: {
    totalCalls: 18,
    successfulCalls: 15,
    failedCalls: 3,
    lastCallTimestamp: "2026-04-06T11:58:00Z",
    p50LatencyMs: 140,
    p95LatencyMs: 280,
    p99LatencyMs: 350,
    providerBreakdown: [
      { provider: "k8sgpt", calls: 10, failedCalls: 2 },
      { provider: "llm-autodrilldown", calls: 8, failedCalls: 1 },
    ],
    scope: "retained_history",
  },
  llmActivity: {
    entries: [
      {
        timestamp: "2026-04-06T12:00:00Z",
        runId: "run-123",
        runLabel: "Daily sweep",
        clusterLabel: "review",
        toolName: "k8sgpt",
        provider: "k8sgpt",
        purpose: "review-enrichment",
        status: "success",
        latencyMs: 180,
        artifactPath: "/artifacts/review-enrichment.json",
        summary: "Review enrichment insight",
        errorSummary: null,
        skipReason: null,
      },
      {
        timestamp: "2026-04-06T11:58:00Z",
        runId: "run-123",
        runLabel: "Daily sweep",
        clusterLabel: "cluster-a",
        toolName: "k8sgpt",
        provider: "k8sgpt",
        purpose: "manual",
        status: "success",
        latencyMs: 120,
        artifactPath: "/artifacts/llm-1.json",
        summary: "analysis ready",
        errorSummary: null,
        skipReason: null,
      },
      {
        timestamp: "2026-04-06T11:57:00Z",
        runId: "run-123",
        runLabel: "Daily sweep",
        clusterLabel: "cluster-b",
        toolName: "llm-autodrilldown",
        provider: "default",
        purpose: "auto-drilldown",
        status: "failed",
        latencyMs: 200,
        artifactPath: "/artifacts/llm-2.json",
        summary: "timeout",
        errorSummary: "provider timeout",
        skipReason: null,
      },
    ],
    summary: {
      retainedEntries: 19,
    },
  },
  llmPolicy: {
    autoDrilldown: {
      enabled: true,
      provider: "default",
      maxPerRun: 3,
      usedThisRun: 1,
      successfulThisRun: 0,
      failedThisRun: 1,
      skippedThisRun: 0,
      budgetExhausted: false,
    },
  },
  providerExecution: {
    autoDrilldown: {
      enabled: true,
      provider: "default",
      maxPerRun: 3,
      eligible: 2,
      attempted: 1,
      succeeded: 0,
      failed: 1,
      skipped: 0,
      unattempted: 1,
      budgetLimited: 1,
      notes: "Reached max per run (3) before the 2nd eligible branch.",
    },
    reviewEnrichment: {
      enabled: true,
      eligible: 1,
      attempted: 1,
      succeeded: 1,
      failed: 0,
      skipped: 0,
      unattempted: 0,
      budgetLimited: null,
      notes: "Review enrichment artifact recorded.",
    },
  },
  reviewEnrichment: {
    status: "success",
    provider: "k8sgpt",
    timestamp: "2026-04-06T12:00:00Z",
    summary: "Review enrichment reshaped the triage order.",
    triageOrder: ["cluster-b", "cluster-a"],
    topConcerns: ["ingress latency", "storage delays"],
    evidenceGaps: ["logs from edge"],
    nextChecks: ["Validate ingress timeouts", "Collect storage metrics"],
    focusNotes: ["Prioritize cluster-b"],
    artifactPath: "/artifacts/review-enrichment.json",
    errorSummary: null,
    skipReason: null,
  },
  nextCheckPlan: {
    status: "success",
    summary: "Planner generated multiple advisory checks.",
    artifactPath: "/artifacts/next-check-plan.json",
    reviewPath: "/artifacts/run-123-review.json",
    enrichmentArtifactPath: "/artifacts/review-enrichment.json",
    candidateCount: sampleNextCheckCandidates.length,
    candidates: sampleNextCheckCandidates,
    orphanedApprovals: [],
    outcomeCounts: [
      { status: "executed-success", count: 1 },
      { status: "approval-required", count: 1 },
      { status: "not-used", count: 1 },
    ],
    orphanedApprovalCount: 0,
  },
  nextCheckQueue: [
    {
      candidateId: "candidate-vague",
      candidateIndex: 1,
      description: "Describe diag CRD for control plane",
      targetCluster: null,
      priorityLabel: "secondary",
      suggestedCommandFamily: "kubectl-describe",
      safeToAutomate: false,
      requiresOperatorApproval: true,
      approvalState: "approval-required",
      executionState: "unexecuted",
      outcomeStatus: "approval-required",
      latestArtifactPath: null,
      sourceReason: "diag-availability",
      expectedSignal: "events",
      normalizationReason: "selection_default",
      safetyReason: "unknown_command",
      approvalReason: "unknown_command",
      duplicateReason: null,
      blockingReason: "unknown_command",
      targetContext: "cluster-b · diag CRD",
      commandPreview: "kubectl describe diag customresourcedefinition --context cluster-b",
      planArtifactPath: "/artifacts/next-check-plan.json",
      queueStatus: "approval-needed",
    },
    {
      candidateId: "candidate-logs",
      candidateIndex: 0,
      description: "Collect kubelet logs for control-plane pods",
      targetCluster: "cluster-a",
      priorityLabel: "primary",
      suggestedCommandFamily: "kubectl-logs",
      safeToAutomate: true,
      requiresOperatorApproval: false,
      approvalState: "not-required",
      executionState: "executed-success",
      outcomeStatus: "executed-success",
      latestArtifactPath: "/artifacts/run-123-next-check-execution-0.json",
      sourceReason: "warning_event_threshold",
      expectedSignal: "logs",
      normalizationReason: "selection_label",
      safetyReason: "known_command",
      approvalReason: null,
      duplicateReason: null,
      blockingReason: null,
      targetContext: "cluster-a · control-plane pods",
      commandPreview: "kubectl logs deployment/control-plane --context cluster-a",
      planArtifactPath: "/artifacts/next-check-plan.json",
      queueStatus: "completed",
    },
    {
      candidateId: "candidate-metrics",
      candidateIndex: 2,
      description: "Capture kubelet metrics for control-plane nodes",
      targetCluster: "cluster-a",
      priorityLabel: "fallback",
      suggestedCommandFamily: "kubectl-get",
      safeToAutomate: false,
      requiresOperatorApproval: true,
      approvalState: "approval-required",
      executionState: "unexecuted",
      outcomeStatus: "not-used",
      latestArtifactPath: null,
      sourceReason: "metric-surge",
      expectedSignal: "metrics",
      normalizationReason: "selection_default",
      safetyReason: "duplicate_evidence",
      approvalReason: "duplicate_evidence",
      duplicateReason: "exact_match",
      blockingReason: "duplicate",
      targetContext: "cluster-a · nodes",
      commandPreview: "kubectl get nodes --context cluster-a",
      planArtifactPath: "/artifacts/next-check-plan.json",
      queueStatus: "duplicate-or-stale",
    },
  ],
  plannerAvailability: {
    status: "planner-present",
    reason: "Planner generated multiple advisory checks.",
    hint: null,
    artifactPath: "/artifacts/next-check-plan.json",
    nextActionHint:
      "Inspect the planner artifact for candidate context before taking any next-check action.",
  },
  nextCheckExecutionHistory: [
    {
      timestamp: "2026-04-06T12:05:00Z",
      clusterLabel: "cluster-a",
      candidateDescription: "Collect kubelet logs for control-plane pods",
      commandFamily: "kubectl-logs",
      status: "success",
      durationMs: 95,
      artifactPath: "/artifacts/run-123-next-check-execution-0.json",
      timedOut: false,
      stdoutTruncated: false,
      stderrTruncated: false,
      outputBytesCaptured: 2048,
    },
    {
      timestamp: "2026-04-06T12:03:00Z",
      clusterLabel: "cluster-b",
      candidateDescription: "Describe diag status",
      commandFamily: "kubectl-describe",
      status: "failed",
      durationMs: 30,
      artifactPath: "/artifacts/run-123-next-check-execution-1.json",
      timedOut: true,
      stdoutTruncated: true,
      stderrTruncated: false,
      outputBytesCaptured: 4096,
    },
  ],
};

export const sampleFleet: FleetPayload = {
  runId: "run-123",
  runLabel: "Daily sweep",
  lastRunTimestamp: "2026-04-06T12:00:00Z",
  topProblem: {
    title: "API pressure",
    detail: "Control plane latency is trending upward",
  },
  fleetStatus: {
    ratingCounts: [
      { rating: "Healthy", count: 5 },
      { rating: "Degraded", count: 2 },
    ],
    degradedClusters: ["cluster-a"],
  },
  clusters: [
    {
      label: "cluster-a",
      context: "prod",
      clusterClass: "primary",
      clusterRole: "control",
      baselineCohort: "tier-1",
      controlPlaneVersion: "v1.28.0",
      healthRating: "Degraded",
      warnings: 2,
      nonRunningPods: 3,
      latestRunTimestamp: "2026-04-06T11:58:00Z",
      topTriggerReason: "High CPU",
      drilldownAvailable: true,
      drilldownTimestamp: "2026-04-06T11:59:00Z",
      missingEvidence: ["logs"],
    },
    {
      label: "cluster-b",
      context: "stage",
      clusterClass: "secondary",
      clusterRole: "worker",
      baselineCohort: "tier-2",
      controlPlaneVersion: "v1.27.5",
      healthRating: "Healthy",
      warnings: 0,
      nonRunningPods: 0,
      latestRunTimestamp: "2026-04-06T11:55:00Z",
      topTriggerReason: "Scheduled maintenance",
      drilldownAvailable: false,
      drilldownTimestamp: null,
      missingEvidence: [],
    },
  ],
  proposalSummary: {
    pending: 3,
    total: 5,
    statusCounts: [
      { status: "pending", count: 3 },
      { status: "review", count: 2 },
        ],
    },
};

export const sampleProposals: ProposalsPayload = {
  statusSummary: [
    { status: "pending", count: 2 },
    { status: "review", count: 1 },
  ],
  proposals: [
    {
      proposalId: "critical-01",
      target: "cluster-a",
      status: "pending",
      confidence: "Critical",
      rationale: "Control plane nodes show CPU pressure across multiple zones.",
      expectedBenefit: "Reduce CPU spikes",
      sourceRunId: "run-123",
      latestNote: null,
      lifecycle: [
        { status: "created", timestamp: "2026-04-06T10:00:00Z", note: "Initial detection" },
      ],
      artifacts: [
        { label: "pressure dump", path: "/artifacts/critical-01.json" },
      ],
    },
    {
      proposalId: "medium-01",
      target: "cluster-b",
      status: "pending",
      confidence: "Medium",
      rationale: "Some nodes restarted after kubelet upgrade.",
      expectedBenefit: "Stabilize kubelet",
      sourceRunId: "run-122",
      latestNote: "Awaiting review",
      lifecycle: [
        { status: "created", timestamp: "2026-04-05T22:00:00Z", note: null },
      ],
      artifacts: [],
    },
    {
      proposalId: "low-01",
      target: "cluster-c",
      status: "review",
      confidence: "Low",
      rationale: "Non-critical upgrades are blocking rollout.",
      expectedBenefit: "Improve rollout predictability",
      sourceRunId: "run-121",
      latestNote: "Waiting for final sign-off",
      lifecycle: [
        { status: "created", timestamp: "2026-04-04T09:00:00Z", note: null },
      ],
      artifacts: [],
    },
  ],
};

export const sampleNotifications: NotificationsPayload = {
  notifications: [
    {
      kind: "Warning",
      summary: "Pod restarts rising",
      timestamp: "2026-04-06T11:45:00Z",
      runId: "run-123",
      clusterLabel: "cluster-a",
      context: "prod",
      details: [
        { label: "Pod", value: "api-server-0" },
        { label: "Reason", value: "OOM" },
      ],
      artifactPath: "/artifacts/notification-1.json",
    },
  ],
  total: 1,
  page: 1,
  limit: 50,
  total_pages: 1,
};

export const sampleClusterDetail: ClusterDetailPayload = {
  selectedClusterLabel: "cluster-a",
  selectedClusterContext: "prod",
  assessment: {
    healthRating: "Degraded",
    missingEvidence: ["events", "logs"],
    probableLayer: "control-plane",
    overallConfidence: "High",
    artifactPath: "/artifacts/cluster-a-assessment.json",
    snapshotPath: "/snapshots/cluster-a.json",
  },
  findings: [
    {
      label: "api-server",
      context: "control-plane",
      triggerReasons: ["Latency spike"],
      warningEvents: 2,
      nonRunningPods: 1,
      summaryEntries: [
        { label: "Latency", value: ">2s p99" },
        { label: "Errors", value: "502" },
      ],
      patternDetails: [
        { label: "Zone", value: "us-west-2" },
        { label: "NodePool", value: "control-plane" },
      ],
      rolloutStatus: ["stable"],
      artifactPath: "/artifacts/finding-api-server.json",
    },
  ],
  hypotheses: [
    {
      description: "High control-plane CPU",
      confidence: "Medium",
      probableLayer: "control-plane",
      falsifier: "CPU stays below 60%",
    },
  ],
  nextChecks: [
    {
      description: "Collect kubelet metrics",
      owner: "platform",
      method: "kubectl top nodes",
      evidenceNeeded: ["node CPU", "node memory"],
    },
  ],
  recommendedAction: {
    actionType: "change",
    description: "Throttle background jobs",
    references: ["doc/limit-jobs"],
    safetyLevel: "change-with-caution",
  },
  drilldownAvailability: {
    totalClusters: 2,
    available: 1,
    missing: 1,
    missingClusters: ["cluster-b"],
  },
  drilldownCoverage: [
    {
      label: "cluster-a",
      context: "prod",
      available: true,
      timestamp: "2026-04-06T11:59:00Z",
      artifactPath: "/artifacts/drilldown-cluster-a.json",
    },
  ],
  relatedProposals: [sampleProposals.proposals[0]],
  relatedNotifications: [sampleNotifications.notifications[0]],
  artifacts: [
    { label: "diagnostic bundle", path: "/artifacts/cluster-a-bundle.json" },
  ],
  nextCheckPlan: sampleNextCheckCandidates,
  topProblem: {
    title: "Control plane saturation",
    detail: "gRPC queues are growing",
  },
};
