import type {
  ClusterDetailPayload,
  DiagnosticPackReview,
  FleetPayload,
  NextCheckPlanCandidate,
  NotificationsPayload,
  ProposalsPayload,
  ProviderExecution,
  ReviewEnrichment,
  ReviewEnrichmentStatus,
  RunPayload,
  RunsListPayload,
} from "../types";

export const sampleRunsList: RunsListPayload = {
  runs: [
    {
      runId: "run-123",
      runLabel: "2026-04-07-1200",
      timestamp: "2026-04-07T12:00:00Z",
      clusterCount: 3,
      triaged: true,
      executionCount: 5,
      reviewedCount: 5,
      reviewStatus: "fully-reviewed",
    },
    {
      runId: "run-122",
      runLabel: "2026-04-07-1100",
      timestamp: "2026-04-07T11:00:00Z",
      clusterCount: 3,
      triaged: false,
      executionCount: 3,
      reviewedCount: 0,
      reviewStatus: "unreviewed",
      reviewDownloadPath: "health/diagnostic-packs/run-122/next_check_usefulness_review.json",
    },
    {
      runId: "run-121",
      runLabel: "2026-04-07-1000",
      timestamp: "2026-04-07T10:00:00Z",
      clusterCount: 2,
      triaged: true,
      executionCount: 2,
      reviewedCount: 1,
      reviewStatus: "partially-reviewed",
    },
    {
      runId: "run-120",
      runLabel: "2026-04-07-0900",
      timestamp: "2026-04-07T09:00:00Z",
      clusterCount: 1,
      triaged: false,
      executionCount: 0,
      reviewedCount: 0,
      reviewStatus: "no-executions",
    },
  ],
  totalCount: 4,
};

export const sampleNextCheckCandidates: NextCheckPlanCandidate[] = [
  {
    description: "Collect kubelet logs for control-plane pods",
    targetCluster: "cluster-a",
    sourceReason: "warning_event_threshold",
    expectedSignal: "logs",
    suggestedCommandFamily: "kubectl-logs",
    safeToAutomate: true,
    requiresOperatorApproval: false,
    riskLevel: "low",
    estimatedCost: "low",
    confidence: "high",
    priorityLabel: "primary",
    gatingReason: null,
    duplicateOfExistingEvidence: false,
    duplicateEvidenceDescription: null,
    candidateId: "candidate-logs",
    candidateIndex: 0,
    approvalStatus: "not-required",
    approvalState: "not-required",
    executionState: "executed-success",
    outcomeStatus: "executed-success",
    latestArtifactPath: "/artifacts/run-123-next-check-execution-0.json",
    latestTimestamp: "2026-04-06T12:05:00Z",
    normalizationReason: "selection_label",
    safetyReason: "known_command",
    approvalReason: null,
    duplicateReason: null,
    blockingReason: null,
    targetContext: "cluster-a · control-plane pods",
    commandPreview: "kubectl logs deployment/control-plane --context cluster-a",
  },
  {
    description: "Describe diag CRD for control plane",
    targetCluster: null,
    sourceReason: "diag-availability",
    expectedSignal: "events",
    suggestedCommandFamily: "kubectl-describe",
    safeToAutomate: false,
    requiresOperatorApproval: true,
    riskLevel: "medium",
    estimatedCost: "medium",
    confidence: "medium",
    priorityLabel: "secondary",
    gatingReason: "Command not recognized or too vague",
    duplicateOfExistingEvidence: false,
    duplicateEvidenceDescription: null,
    candidateId: "candidate-describe",
    candidateIndex: 1,
    approvalStatus: "approval-required",
    approvalState: "approval-required",
    executionState: "unexecuted",
    outcomeStatus: "approval-required",
    latestArtifactPath: null,
    latestTimestamp: null,
    normalizationReason: "selection_default",
    safetyReason: "unknown_command",
    approvalReason: "unknown_command",
    duplicateReason: null,
    blockingReason: "unknown_command",
    targetContext: "cluster-b · diag CRD",
    commandPreview: "kubectl describe diag customresourcedefinition --context cluster-b",
  },
  {
    description: "Capture kubelet metrics for control-plane nodes",
    targetCluster: "cluster-a",
    sourceReason: "metric-surge",
    expectedSignal: "metrics",
    suggestedCommandFamily: "kubectl-get",
    safeToAutomate: false,
    requiresOperatorApproval: true,
    riskLevel: "medium",
    estimatedCost: "medium",
    confidence: "low",
    priorityLabel: "fallback",
    gatingReason: "Matches deterministic next check: Collect kubelet metrics",
    duplicateOfExistingEvidence: true,
    duplicateEvidenceDescription: "Collect kubelet metrics",
    candidateId: "candidate-metrics",
    candidateIndex: 2,
    approvalStatus: "not-required",
    approvalState: "not-required",
    executionState: "unexecuted",
    outcomeStatus: "not-used",
    latestArtifactPath: null,
    latestTimestamp: null,
    normalizationReason: "selection_default",
    safetyReason: "duplicate_evidence",
    approvalReason: "duplicate_evidence",
    duplicateReason: "exact_match",
    blockingReason: "duplicate",
    targetContext: "cluster-a · nodes",
    commandPreview: "kubectl get nodes --context cluster-a",
  },
];

export const sampleDiagnosticPackReview: DiagnosticPackReview = {
  timestamp: "2026-04-06T12:02:00Z",
  summary: "Review detected ranking mismatches and suggested additional confirmation steps.",
  majorDisagreements: [
    "cluster-b priority order conflicts with deterministic assessment",
    "planner ranked storage downstream of networking despite earlier alerts",
  ],
  missingChecks: [
    "Validate storage latency from cluster-b",
    "Capture node drain readiness for cluster-a",
  ],
  rankingIssues: [
    "Top recommendations favor low-utility checks",
    "Evidence-sourced prioritization differs from deterministic triggers",
  ],
  genericChecks: [
    "Review kubelet logs before escalating",
    "Double-check baseline release parity",
  ],
  recommendedNextActions: [
    "Confirm drift detection before reordering planner queue",
    "Survey provider-proposed actions with operator",
  ],
  driftMisprioritized: true,
  confidence: "medium",
  providerStatus: "provider-ok",
  providerSummary: "Provider k8sgpt validated the review and provided metadata.",
  providerErrorSummary: null,
  providerSkipReason: null,
  providerReview: { source: "k8sgpt", score: 0.92 },
  artifactPath: "/artifacts/diagnostic-pack-review.json",
};

export const makeDiagnosticPackReview = (
  overrides: Partial<DiagnosticPackReview> = {}
): DiagnosticPackReview => ({
  ...sampleDiagnosticPackReview,
  ...overrides,
  majorDisagreements:
    overrides.majorDisagreements ?? [...sampleDiagnosticPackReview.majorDisagreements],
  missingChecks: overrides.missingChecks ?? [...sampleDiagnosticPackReview.missingChecks],
  rankingIssues: overrides.rankingIssues ?? [...sampleDiagnosticPackReview.rankingIssues],
  genericChecks: overrides.genericChecks ?? [...sampleDiagnosticPackReview.genericChecks],
  recommendedNextActions:
    overrides.recommendedNextActions ?? [...sampleDiagnosticPackReview.recommendedNextActions],
});

export const sampleReviewEnrichmentStatus: ReviewEnrichmentStatus = {
  status: "success",
  reason: "Review enrichment succeeded and produced insights.",
  provider: "k8sgpt",
  policyEnabled: true,
  providerConfigured: true,
  adapterAvailable: true,
  runEnabled: true,
  runProvider: "k8sgpt",
};

export const makeReviewEnrichmentStatus = (
  overrides: Partial<ReviewEnrichmentStatus> = {}
): ReviewEnrichmentStatus => ({
  ...sampleReviewEnrichmentStatus,
  ...overrides,
});

export const sampleProviderExecution: ProviderExecution = {
  autoDrilldown: {
    enabled: true,
    provider: "default",
    maxPerRun: 3,
    eligible: 2,
    attempted: 1,
    succeeded: 0,
    failed: 1,
    skipped: 0,
    unattempted: 1,
    budgetLimited: 1,
    notes: "Reached max per run (3) before the 2nd eligible branch.",
  },
  reviewEnrichment: {
    enabled: true,
    provider: "k8sgpt",
    maxPerRun: 1,
    eligible: 1,
    attempted: 1,
    succeeded: 1,
    failed: 0,
    skipped: 0,
    unattempted: 0,
    budgetLimited: null,
    notes: "Review enrichment artifact recorded.",
  },
};

export const makeProviderExecution = (
  overrides: Partial<ProviderExecution> = {}
): ProviderExecution => ({
  autoDrilldown: {
    ...sampleProviderExecution.autoDrilldown,
    ...overrides.autoDrilldown,
  },
  reviewEnrichment:
    overrides.reviewEnrichment === undefined
      ? sampleProviderExecution.reviewEnrichment
      : overrides.reviewEnrichment,
});

export const sampleRun: RunPayload = {
  runId: "run-123",
  label: "Daily sweep",
  timestamp: "2026-04-06T12:00:00Z",
  collectorVersion: "collector:v1.2.0",
  clusterCount: 2,
  drilldownCount: 5,
  proposalCount: 4,
  externalAnalysisCount: 1,
  notificationCount: 2,
  artifacts: [
    { label: "run manifest", path: "/artifacts/run-manifest.json" },
  ],
  runStats: {
    lastRunDurationSeconds: 32,
    totalRuns: 12,
    p50RunDurationSeconds: 24,
    p95RunDurationSeconds: 48,
    p99RunDurationSeconds: 64,
  },
  llmStats: {
    totalCalls: 3,
    successfulCalls: 2,
    failedCalls: 1,
    lastCallTimestamp: "2026-04-06T11:59:00Z",
    p50LatencyMs: 110,
    p95LatencyMs: 220,
    p99LatencyMs: 300,
    providerBreakdown: [
      { provider: "k8sgpt", calls: 2, failedCalls: 0 },
      { provider: "default", calls: 1, failedCalls: 1 },
    ],
    scope: "current_run",
  },
  historicalLlmStats: {
    totalCalls: 18,
    successfulCalls: 15,
    failedCalls: 3,
    lastCallTimestamp: "2026-04-06T11:58:00Z",
    p50LatencyMs: 140,
    p95LatencyMs: 280,
    p99LatencyMs: 350,
    providerBreakdown: [
      { provider: "k8sgpt", calls: 10, failedCalls: 2 },
      { provider: "llm-autodrilldown", calls: 8, failedCalls: 1 },
    ],
    scope: "retained_history",
  },
  llmActivity: {
    entries: [
      {
        timestamp: "2026-04-06T12:00:00Z",
        runId: "run-123",
        runLabel: "Daily sweep",
        clusterLabel: "review",
        toolName: "k8sgpt",
        provider: "k8sgpt",
        purpose: "review-enrichment",
        status: "success",
        latencyMs: 180,
        artifactPath: "/artifacts/review-enrichment.json",
        summary: "Review enrichment insight",
        errorSummary: null,
        skipReason: null,
      },
      {
        timestamp: "2026-04-06T11:58:00Z",
        runId: "run-123",
        runLabel: "Daily sweep",
        clusterLabel: "cluster-a",
        toolName: "k8sgpt",
        provider: "k8sgpt",
        purpose: "manual",
        status: "success",
        latencyMs: 120,
        artifactPath: "/artifacts/llm-1.json",
        summary: "analysis ready",
        errorSummary: null,
        skipReason: null,
      },
      {
        timestamp: "2026-04-06T11:57:00Z",
        runId: "run-123",
        runLabel: "Daily sweep",
        clusterLabel: "cluster-b",
        toolName: "llm-autodrilldown",
        provider: "default",
        purpose: "auto-drilldown",
        status: "failed",
        latencyMs: 200,
        artifactPath: "/artifacts/llm-2.json",
        summary: "timeout",
        errorSummary: "provider timeout",
        skipReason: null,
      },
    ],
    summary: {
      retainedEntries: 19,
    },
  },
  llmPolicy: {
    autoDrilldown: {
      enabled: true,
      provider: "default",
      maxPerRun: 3,
      usedThisRun: 1,
      successfulThisRun: 0,
      failedThisRun: 1,
      skippedThisRun: 0,
      budgetExhausted: false,
    },
  },
  providerExecution: sampleProviderExecution,
  reviewEnrichment: {
    status: "success",
    provider: "k8sgpt",
    timestamp: "2026-04-06T12:00:00Z",
    summary: "Review enrichment reshaped the triage order.",
    triageOrder: ["cluster-b", "cluster-a"],
    topConcerns: ["ingress latency", "storage delays"],
    evidenceGaps: ["logs from edge"],
    nextChecks: ["Validate ingress timeouts", "Collect storage metrics"],
    focusNotes: ["Prioritize cluster-b"],
    artifactPath: "/artifacts/review-enrichment.json",
    errorSummary: null,
    skipReason: null,
  },
  reviewEnrichmentStatus: sampleReviewEnrichmentStatus,
  nextCheckPlan: {
    summary: "Planner generated multiple advisory checks.",
    artifactPath: "/artifacts/next-check-plan.json",
    reviewPath: "/artifacts/run-123-review.json",
    enrichmentArtifactPath: "/artifacts/review-enrichment.json",
    candidateCount: sampleNextCheckCandidates.length,
    candidates: sampleNextCheckCandidates,
    orphanedApprovals: [],
    outcomeCounts: [
      { status: "executed-success", count: 1 },
      { status: "approval-required", count: 1 },
      { status: "not-used", count: 1 },
    ],
    orphanedApprovalCount: 0,
  },
  deterministicNextChecks: {
    clusterCount: 1,
    totalNextCheckCount: 6,
    clusters: [
      {
        label: "cluster-a",
        context: "prod",
        topProblem: "High CPU",
        deterministicNextCheckCount: 6,
        deterministicNextCheckSummaries: [
          {
            description: "Capture tcpdump",
            owner: "platform",
            method: "kubectl exec",
            evidenceNeeded: ["tcpdump output"],
            priorityScore: 95,
            workstream: "incident",
            urgency: "high",
            isPrimaryTriage: true,
            whyNow: "Immediate triage for High CPU",
          },
          {
            description: "Collect kubelet logs for web deployment",
            owner: "platform",
            method: "kubectl logs",
            evidenceNeeded: ["kubectl logs deployment/web"],
            priorityScore: 88,
            workstream: "incident",
            urgency: "high",
            isPrimaryTriage: true,
            whyNow: "Immediate triage for High CPU",
          },
          {
            description: "Inspect readiness probes for web-frontend",
            owner: "platform",
            method: "kubectl describe pod",
            evidenceNeeded: ["kubectl describe pod web-frontend"],
            priorityScore: 75,
            workstream: "incident",
            urgency: "high",
            isPrimaryTriage: false,
            whyNow: "Immediate triage for High CPU",
          },
          {
            description: "Review node conditions for control-plane hosts",
            owner: "platform",
            method: "kubectl get nodes",
            evidenceNeeded: ["kubectl describe nodes"],
            priorityScore: 68,
            workstream: "incident",
            urgency: "medium",
            isPrimaryTriage: false,
            whyNow: "Immediate triage for High CPU",
          },
          {
            description: "Collect kubelet metrics from nodes",
            owner: "platform",
            method: "kubectl get --raw /metrics",
            evidenceNeeded: ["kubelet metrics"],
            priorityScore: 50,
            workstream: "evidence",
            urgency: "medium",
            isPrimaryTriage: false,
            whyNow: "Gather additional evidence",
          },
          {
            description: "Compare baseline release parity",
            owner: "platform engineer",
            method: "kubectl get helmrelease",
            evidenceNeeded: ["helm release list"],
            priorityScore: 25,
            workstream: "drift",
            urgency: "low",
            isPrimaryTriage: false,
            whyNow: "Baseline drift follow-up",
          },
        ],
        drilldownAvailable: true,
        assessmentArtifactPath: "/artifacts/cluster-a-assessment.json",
        drilldownArtifactPath: "/artifacts/drilldown-cluster-a.json",
      },
    ],
  },
  nextCheckQueue: [
    {
      candidateId: "candidate-vague",
      candidateIndex: 1,
      description: "Describe diag CRD for control plane",
      targetCluster: null,
      priorityLabel: "secondary",
      suggestedCommandFamily: "kubectl-describe",
      safeToAutomate: false,
      requiresOperatorApproval: true,
      approvalState: "approval-required",
      executionState: "unexecuted",
      outcomeStatus: "approval-required",
      latestArtifactPath: null,
      sourceReason: "diag-availability",
      expectedSignal: "events",
      normalizationReason: "selection_default",
      safetyReason: "unknown_command",
      approvalReason: "unknown_command",
      duplicateReason: null,
      blockingReason: "unknown_command",
      targetContext: "cluster-b · diag CRD",
      commandPreview: "kubectl describe diag customresourcedefinition --context cluster-b",
      planArtifactPath: "external-analysis/run-123-next-check-plan.json",
      queueStatus: "approval-needed",
      failureClass: "approval-missing-or-stale",
      priorityRationale: "Approval required before execution",
      failureSummary: "Candidate requires operator approval before execution.",
      suggestedNextOperatorMove: "Review approval state",
    },
    {
      candidateId: "candidate-logs",
      candidateIndex: 0,
      description: "Collect kubelet logs for control-plane pods",
      targetCluster: "cluster-a",
      priorityLabel: "primary",
      suggestedCommandFamily: "kubectl-logs",
      safeToAutomate: true,
      requiresOperatorApproval: false,
      approvalState: "not-required",
      executionState: "executed-success",
      outcomeStatus: "executed-success",
      latestArtifactPath: "/artifacts/run-123-next-check-execution-0.json",
      sourceReason: "warning_event_threshold",
      expectedSignal: "logs",
      normalizationReason: "selection_label",
      safetyReason: "known_command",
      approvalReason: null,
      duplicateReason: null,
      blockingReason: null,
      targetContext: "cluster-a · control-plane pods",
      commandPreview: "kubectl logs deployment/control-plane --context cluster-a",
      planArtifactPath: "external-analysis/run-123-next-check-plan.json",
      queueStatus: "completed",
      resultClass: "useful-signal",
      resultSummary: "Captured control-plane logs that highlight recent kubelet errors.",
      suggestedNextOperatorMove: "Correlate this output with the target incident.",
    },
    {
      candidateId: "candidate-metrics",
      candidateIndex: 2,
      description: "Capture kubelet metrics for control-plane nodes",
      targetCluster: "cluster-a",
      priorityLabel: "fallback",
      suggestedCommandFamily: "kubectl-get",
      safeToAutomate: false,
      requiresOperatorApproval: true,
      approvalState: "approval-required",
      executionState: "unexecuted",
      outcomeStatus: "not-used",
      latestArtifactPath: null,
      sourceReason: "metric-surge",
      expectedSignal: "metrics",
      normalizationReason: "selection_default",
      safetyReason: "duplicate_evidence",
      approvalReason: "duplicate_evidence",
      duplicateReason: "exact_match",
      blockingReason: "duplicate",
      targetContext: "cluster-a · nodes",
      commandPreview: "kubectl get nodes --context cluster-a",
      planArtifactPath: "external-analysis/run-123-next-check-plan.json",
      queueStatus: "duplicate-or-stale",
    },
    {
      candidateId: "candidate-storage",
      candidateIndex: 3,
      description: "Collect storage latency metrics",
      targetCluster: "cluster-b",
      priorityLabel: "primary",
      suggestedCommandFamily: "kubectl-get",
      safeToAutomate: true,
      requiresOperatorApproval: false,
      approvalState: "not-required",
      executionState: "unexecuted",
      outcomeStatus: "not-used",
      latestArtifactPath: null,
      latestTimestamp: "2026-04-06T12:07:00Z",
      sourceReason: "storage-latency",
      expectedSignal: "metrics",
      normalizationReason: "selection_default",
      safetyReason: "known_command",
      approvalReason: null,
      duplicateReason: null,
      blockingReason: null,
      targetContext: "cluster-b · storage",
      commandPreview: "kubectl get pv --context cluster-b",
      planArtifactPath: "external-analysis/run-123-next-check-plan.json",
      queueStatus: "safe-ready",
    },
    {
      candidateId: "candidate-approved",
      candidateIndex: 4,
      description: "Validate networking policies",
      targetCluster: "cluster-a",
      priorityLabel: "secondary",
      suggestedCommandFamily: "kubectl-get",
      safeToAutomate: true,
      requiresOperatorApproval: true,
      approvalState: "approved",
      executionState: "unexecuted",
      outcomeStatus: "approved",
      latestArtifactPath: "/artifacts/approval-1.json",
      latestTimestamp: "2026-04-06T12:08:00Z",
      sourceReason: "network-policy",
      expectedSignal: "policy",
      normalizationReason: "selection_label",
      safetyReason: "known_command",
      approvalReason: "policy_reviewed",
      duplicateReason: null,
      blockingReason: null,
      targetContext: "cluster-a · networking",
      commandPreview: "kubectl get networkpolicies --context cluster-a",
      planArtifactPath: "external-analysis/run-123-next-check-plan.json",
      queueStatus: "approved-ready",
    },
    {
      candidateId: "candidate-failed",
      candidateIndex: 5,
      description: "Inspect etcd leader",
      targetCluster: "cluster-b",
      priorityLabel: "secondary",
      suggestedCommandFamily: "kubectl-get",
      safeToAutomate: false,
      requiresOperatorApproval: false,
      approvalState: "not-required",
      executionState: "executed-failed",
      outcomeStatus: "executed-failed",
      latestArtifactPath: "/artifacts/run-123-next-check-execution-1.json",
      latestTimestamp: "2026-04-06T12:03:30Z",
      sourceReason: "etcd-candidate",
      expectedSignal: "events",
      normalizationReason: "selection_default",
      safetyReason: "known_command",
      approvalReason: null,
      duplicateReason: null,
      blockingReason: null,
      targetContext: "cluster-b · etcd",
      commandPreview: "kubectl get endpoints --context cluster-b",
      planArtifactPath: "external-analysis/run-123-next-check-plan.json",
      queueStatus: "failed",
      failureClass: "command-failed",
      failureSummary: "Command returned a non-zero exit code.",
      suggestedNextOperatorMove: "Inspect artifact output",
    },
  ],
  plannerAvailability: {
    status: "planner-present",
    reason: "Planner generated multiple advisory checks.",
    hint: null,
    artifactPath: "/artifacts/next-check-plan.json",
    nextActionHint:
      "Inspect the planner artifact for candidate context before taking any next-check action.",
  },
  diagnosticPackReview: sampleDiagnosticPackReview,
  diagnosticPack: {
    path: "/artifacts/run-123-diagnostic-pack.zip",
    timestamp: "2026-04-06T12:01:00Z",
    label: "Run 123 pack",
  },
  nextCheckExecutionHistory: [
    {
      timestamp: "2026-04-06T12:05:00Z",
      clusterLabel: "cluster-a",
      candidateDescription: "Collect kubelet logs for control-plane pods",
      commandFamily: "kubectl-logs",
      status: "success",
      durationMs: 95,
      artifactPath: "/artifacts/run-123-next-check-execution-0.json",
      timedOut: false,
      stdoutTruncated: false,
      stderrTruncated: false,
      outputBytesCaptured: 2048,
      resultClass: "useful-signal",
      resultSummary: "Logs include control-plane errors useful for diagnosing the incident.",
      suggestedNextOperatorMove: "Correlate these logs with the ongoing incident timeline.",
    },
    {
      timestamp: "2026-04-06T12:03:00Z",
      clusterLabel: "cluster-b",
      candidateDescription: "Describe diag status",
      commandFamily: "kubectl-describe",
      status: "failed",
      durationMs: 30,
      artifactPath: "/artifacts/run-123-next-check-execution-1.json",
      timedOut: true,
      stdoutTruncated: true,
      stderrTruncated: false,
      outputBytesCaptured: 4096,
      failureClass: "timed-out",
      failureSummary: "Command timed out.",
      suggestedNextOperatorMove: "Retry candidate",
    },
  ],
};

export const makeRunWithOverrides = (overrides: Partial<RunPayload> = {}): RunPayload => {
  const base = JSON.parse(JSON.stringify(sampleRun)) as RunPayload;
  return {
    ...base,
    ...overrides,
  };
};

export const sampleFleet: FleetPayload = {
  runId: "run-123",
  runLabel: "Daily sweep",
  lastRunTimestamp: "2026-04-06T12:00:00Z",
  topProblem: {
    title: "API pressure",
    detail: "Control plane latency is trending upward",
  },
  fleetStatus: {
    ratingCounts: [
      { rating: "Healthy", count: 5 },
      { rating: "Degraded", count: 2 },
    ],
    degradedClusters: ["cluster-a"],
  },
  clusters: [
    {
      label: "cluster-a",
      context: "prod",
      clusterClass: "primary",
      clusterRole: "control",
      baselineCohort: "tier-1",
      controlPlaneVersion: "v1.28.0",
      healthRating: "Degraded",
      warnings: 2,
      nonRunningPods: 3,
      latestRunTimestamp: "2026-04-06T11:58:00Z",
      topTriggerReason: "High CPU",
      drilldownAvailable: true,
      drilldownTimestamp: "2026-04-06T11:59:00Z",
      missingEvidence: ["logs"],
    },
    {
      label: "cluster-b",
      context: "stage",
      clusterClass: "secondary",
      clusterRole: "worker",
      baselineCohort: "tier-2",
      controlPlaneVersion: "v1.27.5",
      healthRating: "Healthy",
      warnings: 0,
      nonRunningPods: 0,
      latestRunTimestamp: "2026-04-06T11:55:00Z",
      topTriggerReason: "Scheduled maintenance",
      drilldownAvailable: false,
      drilldownTimestamp: null,
      missingEvidence: [],
    },
  ],
  proposalSummary: {
    pending: 3,
    total: 5,
    statusCounts: [
      { status: "pending", count: 3 },
      { status: "review", count: 2 },
        ],
    },
};

export const sampleProposals: ProposalsPayload = {
  statusSummary: [
    { status: "pending", count: 2 },
    { status: "review", count: 1 },
  ],
  proposals: [
    {
      proposalId: "critical-01",
      target: "cluster-a",
      status: "pending",
      confidence: "Critical",
      rationale: "Control plane nodes show CPU pressure across multiple zones.",
      expectedBenefit: "Reduce CPU spikes",
      sourceRunId: "run-123",
      latestNote: null,
      lifecycle: [
        { status: "created", timestamp: "2026-04-06T10:00:00Z", note: "Initial detection" },
      ],
      artifacts: [
        { label: "pressure dump", path: "/artifacts/critical-01.json" },
      ],
    },
    {
      proposalId: "medium-01",
      target: "cluster-b",
      status: "pending",
      confidence: "Medium",
      rationale: "Some nodes restarted after kubelet upgrade.",
      expectedBenefit: "Stabilize kubelet",
      sourceRunId: "run-122",
      latestNote: "Awaiting review",
      lifecycle: [
        { status: "created", timestamp: "2026-04-05T22:00:00Z", note: null },
      ],
      artifacts: [],
    },
    {
      proposalId: "low-01",
      target: "cluster-c",
      status: "review",
      confidence: "Low",
      rationale: "Non-critical upgrades are blocking rollout.",
      expectedBenefit: "Improve rollout predictability",
      sourceRunId: "run-121",
      latestNote: "Waiting for final sign-off",
      lifecycle: [
        { status: "created", timestamp: "2026-04-04T09:00:00Z", note: null },
      ],
      artifacts: [],
    },
  ],
};

export const sampleNotifications: NotificationsPayload = {
  notifications: [
    {
      kind: "Warning",
      summary: "Pod restarts rising",
      timestamp: "2026-04-06T11:45:00Z",
      runId: "run-123",
      clusterLabel: "cluster-a",
      context: "prod",
      details: [
        { label: "Pod", value: "api-server-0" },
        { label: "Reason", value: "OOM" },
      ],
      artifactPath: "/artifacts/notification-1.json",
    },
  ],
  total: 1,
  page: 1,
  limit: 50,
  total_pages: 1,
};

export const sampleClusterDetail: ClusterDetailPayload = {
  selectedClusterLabel: "cluster-a",
  selectedClusterContext: "prod",
  assessment: {
    healthRating: "Degraded",
    missingEvidence: ["events", "logs"],
    probableLayer: "control-plane",
    overallConfidence: "High",
    artifactPath: "/artifacts/cluster-a-assessment.json",
    snapshotPath: "/snapshots/cluster-a.json",
  },
  findings: [
    {
      label: "api-server",
      context: "control-plane",
      triggerReasons: ["Latency spike"],
      warningEvents: 2,
      nonRunningPods: 1,
      summaryEntries: [
        { label: "Latency", value: ">2s p99" },
        { label: "Errors", value: "502" },
      ],
      patternDetails: [
        { label: "Zone", value: "us-west-2" },
        { label: "NodePool", value: "control-plane" },
      ],
      rolloutStatus: ["stable"],
      artifactPath: "/artifacts/finding-api-server.json",
    },
  ],
  hypotheses: [
    {
      description: "High control-plane CPU",
      confidence: "Medium",
      probableLayer: "control-plane",
      falsifier: "CPU stays below 60%",
    },
  ],
  nextChecks: [
    {
      description: "Collect kubelet metrics",
      owner: "platform",
      method: "kubectl top nodes",
      evidenceNeeded: ["node CPU", "node memory"],
    },
  ],
  recommendedAction: {
    actionType: "change",
    description: "Throttle background jobs",
    references: ["doc/limit-jobs"],
    safetyLevel: "change-with-caution",
  },
  drilldownAvailability: {
    totalClusters: 2,
    available: 1,
    missing: 1,
    missingClusters: ["cluster-b"],
  },
  drilldownCoverage: [
    {
      label: "cluster-a",
      context: "prod",
      available: true,
      timestamp: "2026-04-06T11:59:00Z",
      artifactPath: "/artifacts/drilldown-cluster-a.json",
    },
  ],
  relatedProposals: [sampleProposals.proposals[0]],
  relatedNotifications: [sampleNotifications.notifications[0]],
  artifacts: [
    { label: "diagnostic bundle", path: "/artifacts/cluster-a-bundle.json" },
  ],
  nextCheckPlan: sampleNextCheckCandidates,
  topProblem: {
    title: "Control plane saturation",
    detail: "gRPC queues are growing",
  },
};
