/**
 * IncidentSnapshotPanel test fixtures
 *
 * Shared mock data for IncidentSnapshotPanel tests.
 */

export const mockSuccessResponse = {
  bundle_id: "default-20260101-120000",
  captured_at: "2026-01-01T12:00:00Z",
  namespace: "default",
  summary: {
    total_pods: 10,
    failing_pods_count: 2,
    total_deployments: 3,
    total_events: 25,
    symptoms_count: 3,
  },
  bundle: {
    metadata: {
      bundle_id: "default-20260101-120000",
      namespace: "default",
    },
    pods: [],
    events: [],
    deployments: [],
    symptoms: [],
  },
};

export const mockErrorResponse = {
  bundle_id: "",
  captured_at: "2026-01-01T12:00:00Z",
  namespace: "default",
  summary: {
    total_pods: 0,
    failing_pods_count: 0,
    total_deployments: 0,
    total_events: 0,
    symptoms_count: 0,
  },
  error: "Namespace not found",
};

export const mockPacketResponse = {
  bundle_id: "default-20260101-120000",
  packet: "# k9b Incident Review Packet\n\n**Generated by k9b**",
  format: "markdown",
};
