#!/usr/bin/env bash
# CI-HERMETIC-TOOLCACHE:
# Wire Docker Buildx from runner tool cache or system PATH.
# Creates a Buildx builder with BuildKit daemon configuration.
#
# Usage:
#   scripts/ci/wire_docker_buildx.sh --buildkitd-config <path> [builder_name]
#
# Arguments:
#   --buildkitd-config  Path to buildkitd.toml configuration file (required)
#   builder_name        Optional builder name (defaults to k9b-{RUN_ID}-{RUN_ATTEMPT})
#
# Environment:
#   GITHUB_RUN_ID        GitHub run ID (used for builder name uniqueness)
#   GITHUB_RUN_ATTEMPT   GitHub run attempt number
#   GITHUB_OUTPUT        Path to GitHub output file (set by GitHub Actions)
#   GITHUB_ENV          Path to GitHub env file (set by GitHub Actions)
#
# Outputs:
#   K9B_BUILDX_BUILDER   Builder name (written to GITHUB_ENV and GITHUB_OUTPUT)
#
# Requirements:
#   - Docker must be available
#   - buildkitd-config file must exist and be readable
#
# See docs/ci-hermetic-toolchain.md

set -euo pipefail

# This script uses docker/buildx which may pull images from Harbor registry.
# Harbor (harbor-pve1.spbnix.local) is configured with proxy-cache for external images.
# The buildkitd.toml is generated by the workflow with proper Harbor CA config.

# Parse arguments
buildkitd_config=""
builder_name=""  # Optional positional argument for explicit builder name

while [[ $# -gt 0 ]]; do
    case "$1" in
        --buildkitd-config)
            buildkitd_config="${2:?missing --buildkitd-config value}"
            shift 2
            ;;
        -*)
            echo "unknown argument: $1" >&2
            echo "Usage: $0 --buildkitd-config <path> [builder_name]" >&2
            exit 2
            ;;
        *)
            # Positional argument: builder name
            if [[ -n "${builder_name}" ]]; then
                echo "unexpected extra positional argument: $1" >&2
                echo "Usage: $0 --buildkitd-config <path> [builder_name]" >&2
                exit 2
            fi
            builder_name="$1"
            shift
            ;;
    esac
done

# Validate required arguments
if [[ -z "${buildkitd_config}" ]]; then
    echo "ERROR: --buildkitd-config is required" >&2
    echo "Usage: $0 --buildkitd-config <path>" >&2
    exit 2
fi

# Validate buildkitd-config file exists
if [[ ! -f "${buildkitd_config}" ]]; then
    echo "ERROR: BuildKit config not found: ${buildkitd_config}" >&2
    exit 1
fi

echo "=== Wiring Docker Buildx ==="
echo "BuildKit config: ${buildkitd_config}"

# Harbor registry for BuildKit daemon image (pulled via Harbor proxy-cache)
HARBOR_REGISTRY="${HARBOR_REGISTRY:-harbor-pve1.spbnix.local}"
# BuildKit image from Harbor proxy-cache for hermetic builds
K9B_BUILDKIT_IMAGE="${K9B_BUILDKIT_IMAGE:-${HARBOR_REGISTRY}/dockerhub-cache/moby/buildkit:buildx-stable-1}"

# Determine builder name: use explicit name if provided, otherwise generate unique one
if [[ -n "${builder_name}" ]]; then
    builder="${builder_name}"
else
    run_id="${GITHUB_RUN_ID:-local}"
    run_attempt="${GITHUB_RUN_ATTEMPT:-0}"
    builder="k9b-${run_id}-${run_attempt}"
fi

echo "Builder name: ${builder}"

# Create Buildx builder with BuildKit daemon configuration
echo "Creating Buildx builder with BuildKit daemon config..."
echo "BuildKit image: ${K9B_BUILDKIT_IMAGE}"
docker buildx create \
    --name "${builder}" \
    --driver docker-container \
    --driver-opt "image=${K9B_BUILDKIT_IMAGE}" \
    --buildkitd-config "${buildkitd_config}" \
    --use \
    --bootstrap

# Inspect builder to verify it was created correctly
echo "=== Inspecting builder ==="
docker buildx inspect "${builder}"

# Export builder name for subsequent steps
# Write to GITHUB_OUTPUT (step-level output)
if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    echo "K9B_BUILDX_BUILDER=${builder}" >> "${GITHUB_OUTPUT}"
    echo "k9b_builder=${builder}" >> "${GITHUB_OUTPUT}"
    echo "name=${builder}" >> "${GITHUB_OUTPUT}"
fi

# Write to GITHUB_ENV (job-level environment)
if [[ -n "${GITHUB_ENV:-}" ]]; then
    echo "K9B_BUILDX_BUILDER=${builder}" >> "${GITHUB_ENV}"
fi

echo "=== Buildx wiring complete ==="
