"""CLI entry point for the audit generator (CORRECTION12).

CORRECTION12: the CLI is a thin wrapper.  The single production
authority that writes audit reports is :class:`ReportLayout`
plus :func:`write_all` and :func:`write_audit`.  The CLI's
:func:`cmd_write` delegates to :func:`write_audit` and never
directly writes a report file itself.

The CLI module is deliberately excluded from importing the
low-level write helpers:

* ``_write_atomic``
* ``_json_dumps``
* ``_dump_helpers_shard``
* ``render_markdown``

so the only legitimate write path is ``write_audit(layout=canonical_layout())``.
``cmd_check`` builds the audit object once and writes a
reproduction into a temporary layout for byte-level comparison;
it never imports the forbidden encoding helpers either.

Usage::

    python scripts/verifiers_audit/audit.py --check
    python scripts/verifiers_audit/audit.py --write
    python scripts/verifiers_audit/audit.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tempfile
from pathlib import Path
from typing import cast

from scripts.verifiers_audit.builder import build_audit_object
from scripts.verifiers_audit.report_io import (
    REPORT_ROOT,
    SHARD_NAMES,
    TOP_LEVEL_JSON,
    AuditWriteError,
    canonical_layout,
    report_layout_for_shard_root,
    write_all,
    write_audit,
)
from scripts.verifiers_audit.validation import run_all


def _load_gate_classification_from_disk() -> dict[str, object] | None:
    """Return the persisted auxiliary record if it exists.

    Falls back to ``None`` when the file is missing or unreadable
    (first-ever run, the user has not yet collected auxiliary
    evidence).  The audit builder in that case produces a
    deterministic ``UNASSESSED`` record.
    """
    path = REPORT_ROOT / "gate_classification.json"
    if not path.exists():
        return None
    try:
        return cast(
            "dict[str, object] | None",
            json.loads(path.read_text(encoding="utf-8")),
        )
    except (OSError, ValueError):
        return None


def cmd_check() -> int:
    """Verify the on-disk reports match the freshly-built audit object.

    The ``--check`` mode exercises the persisted
    ``gate_classification.json`` (or, if missing, generates an
    ``UNASSESSED`` record).  The audit object itself never
    runs the canonical gate; the auxiliary two-tree experiment
    is the only path that produces a real classification.

    The persisted ``gate_classification.json`` is loaded from
    disk (or, if missing, generated by the audit object as an
    ``UNASSESSED`` record) so the in-memory and on-disk copies
    match.

    CORRECTION12: the comparison is driven by writing the
    in-memory audit into a temporary :class:`ReportLayout` via
    :func:`write_all` and then byte-comparing each artifact
    against the canonical on-disk file.  The CLI never imports
    the low-level encoding helpers.
    """
    gate_classification = _load_gate_classification_from_disk()
    audit = build_audit_object(
        {}, gate_classification=gate_classification
    )
    failures: list[str] = []

    ok, validator_failures = run_all(audit)
    if not ok:
        failures.append("validators: " + ", ".join(validator_failures))

    with tempfile.TemporaryDirectory() as tmp_root:
        tmp_reports = Path(tmp_root) / "reports"
        tmp_reports.mkdir(parents=True, exist_ok=True)
        # Mirror the on-disk gate_classification into the
        # temporary layout so write_all records the same hash
        # the canonical run produced.
        canonical_gc = REPORT_ROOT / "gate_classification.json"
        if canonical_gc.exists():
            # The CLI does not own the gate_classification
            # shard; it is a read-only consumer of the
            # canonical artifact.  ``shutil.copy2`` mirrors the
            # file into the temporary layout so ``write_all``
            # records the same hash the canonical run produced.
            shutil.copy2(canonical_gc, tmp_reports / "gate_classification.json")
        tmp_layout = report_layout_for_shard_root(tmp_reports)
        write_all(layout=tmp_layout, audit=audit)

        # Compare each shard by sha256 hash.  The path field in
        # the shard manifest is ignored because the canonical
        # layout records repo-relative paths while the tmp
        # layout records absolute paths (the two have no common
        # prefix on macOS due to /private/var vs /Users).
        for name in SHARD_NAMES:
            tmp_path = tmp_layout.shard_root / f"{name}.json"
            if not tmp_path.exists():
                failures.append(f"shard missing: {name}")
                continue
            actual_on_disk = REPORT_ROOT / f"{name}.json"
            if not actual_on_disk.exists():
                failures.append(f"shard missing on disk: {name}")
                continue
            expected_h = hashlib.sha256(tmp_path.read_bytes()).hexdigest()
            actual_h = hashlib.sha256(actual_on_disk.read_bytes()).hexdigest()
            if expected_h != actual_h:
                failures.append(f"shard drift: {name}")

        if TOP_LEVEL_JSON.exists():
            # The top-level index drift is tolerated by hash
            # comparison instead of byte comparison.  The path
            # fields of the shards are environmental (absolute
            # in tmp layouts, repo-relative in canonical layouts).
            tmp_idx = json.loads(
                tmp_layout.top_level_json.read_text(encoding="utf-8")
            )
            on_disk_idx = json.loads(
                TOP_LEVEL_JSON.read_text(encoding="utf-8")
            )
            tmp_shards = tmp_idx.get("shards", {})
            disk_shards = on_disk_idx.get("shards", {})
            if tmp_shards.keys() != disk_shards.keys():
                failures.append("top-level index shard-set drift")
            for name, info in tmp_shards.items():
                disk_info = disk_shards.get(name, {})
                if info.get("sha256") != disk_info.get("sha256"):
                    failures.append(f"top-level index shard drift: {name}")

        canonical_md = canonical_layout().markdown_path
        if canonical_md.exists():
            expected_h = hashlib.sha256(
                tmp_layout.markdown_path.read_bytes()
            ).hexdigest()
            actual_h = hashlib.sha256(canonical_md.read_bytes()).hexdigest()
            if expected_h != actual_h:
                failures.append("markdown drift")


    if failures:
        print("FAIL: " + "; ".join(failures), file=sys.stderr)
        return 2
    print("PASS: audit object matches on-disk reports")
    return 0


def cmd_write(
    gate_classification: dict[str, object] | None = None,
) -> int:
    """Write the audit set via the sole production writer.

    CORRECTION12: the CLI is a thin wrapper.  ``cmd_write``
    delegates to :func:`write_audit` (the sole production
    writer) and never directly writes a report file itself.

    When ``gate_classification`` is supplied the call is
    rejected BEFORE any side effect, with exit code 2.  At
    most one write_audit invocation is performed per call;
    a writer failure (``OSError``, ``ValueError``, or
    :class:`AuditWriteError`) is reported on stderr and exits 1.
    """
    if gate_classification is not None:
        print(
            "ERROR: caller-supplied gate_classification is forbidden",
            file=sys.stderr,
        )
        return 2

    try:
        write_audit(layout=canonical_layout())
    except (OSError, ValueError, AuditWriteError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    grp = parser.add_mutually_exclusive_group(required=True)
    grp.add_argument("--check", action="store_true", help="Verify reports are up to date.")
    grp.add_argument("--write", action="store_true", help="Write reports.")
    args = parser.parse_args(argv)
    if args.check:
        return cmd_check()
    if args.write:
        return cmd_write()
    return 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
