"""CLI entry point for the audit generator.

Usage::

    python scripts/verifiers_audit/audit.py --check
    python scripts/verifiers_audit/audit.py --write
    python scripts/verifiers_audit/audit.py --check
"""

from __future__ import annotations

# mypy: disable-error-code="type-arg,no-any-return,index,assignment,arg-type,union-attr"
import argparse
import hashlib
import os
import sys

from scripts.verifiers_audit.builder import build_audit_object
from scripts.verifiers_audit.discovery import REPO_ROOT
from scripts.verifiers_audit.render import MARKDOWN_PATH, render_markdown
from scripts.verifiers_audit.report_io import (
    REPORT_ROOT,
    SHARD_NAMES,
    TOP_LEVEL_JSON,
    _dump_helpers_shard,
    _json_dumps,
)
from scripts.verifiers_audit.validation import run_all


def _hash_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def _encode(name: str, shard: object) -> bytes:
    # The ``helpers`` shard is hand-assembled so every helper
    # dict renders on a single line (a 74-helper shard otherwise
    # overflows the 500-line LLM-friendly threshold).  Every
    # other shard uses the standard ``_json_dumps`` encoding.
    if name == "helpers":
        return _dump_helpers_shard(shard)
    return _json_dumps(shard)


def cmd_check() -> int:
    """Verify the on-disk reports match the freshly-built audit object.

    The ``--check`` mode runs the canonical gate to keep the
    on-disk evidence aligned with the freshly-built audit object.
    Use ``AUDIT01_SKIP_GATE=1`` (or pass ``--skip-gate``) only
    for fast local sanity checks; the resulting report would be
    labelled ``SKIPPED`` and must NOT be used as closure
    evidence.

    The persisted ``gate_classification.json`` is loaded from
    disk (or, if missing, generated by the audit object as an
    ``UNASSESSED`` record) so the in-memory and on-disk copies
    match.
    """
    skip_gate = os.environ.get("AUDIT01_SKIP_GATE") == "1"
    gate_classification = _load_gate_classification_from_disk()
    audit = build_audit_object(
        {}, skip_gate=skip_gate, gate_classification=gate_classification
    )
    failures: list[str] = []

    ok, validator_failures = run_all(audit)
    if not ok:
        failures.append("validators: " + ", ".join(validator_failures))

    shard_hashes: dict[str, str] = {}
    for name in SHARD_NAMES:
        body = _encode(name, audit[name])
        shard_hashes[name] = hashlib.sha256(body).hexdigest()

    audit["index"]["shards"] = {
        name: {
            "path": str((REPORT_ROOT / f"{name}.json").relative_to(REPO_ROOT)),
            "sha256": shard_hashes[name],
        }
        for name in SHARD_NAMES
    }

    for name in SHARD_NAMES:
        shard_path = REPORT_ROOT / f"{name}.json"
        if not shard_path.exists():
            failures.append(f"shard missing: {name}")
            continue
        expected = _encode(name, audit[name])
        actual = shard_path.read_bytes()
        if expected != actual:
            failures.append(f"shard drift: {name}")

    if TOP_LEVEL_JSON.exists():
        expected_idx = _json_dumps(audit["index"])
        actual_idx = TOP_LEVEL_JSON.read_bytes()
        if expected_idx != actual_idx:
            failures.append("top-level index drift")

    if MARKDOWN_PATH.exists():
        expected_md = render_markdown(audit).encode("utf-8")
        actual_md = MARKDOWN_PATH.read_bytes()
        if expected_md != actual_md:
            failures.append("markdown drift")

    if failures:
        print("FAIL: " + "; ".join(failures), file=sys.stderr)
        return 2
    digest = _hash_bytes(_json_dumps(audit["index"]))
    print(f"PASS: audit object matches on-disk reports ({digest})")
    return 0


# Shards that ``audit.py --write`` owns.  ``gate_classification``
# is intentionally NOT in this set: it is owned exclusively by
# ``scripts/verifiers_audit/collect_r2_evidence.py`` so the fast
# report-generation flow never overwrites a real evidence shard
# with a ``SKIPPED`` placeholder.
WRITE_OWNED_SHARDS: tuple[str, ...] = (
    "inventory",
    "helpers",
    "groups",
    "core_usage",
    "candidates",
    "source_preservation",
)


def _load_gate_classification_from_disk() -> dict[str, object] | None:
    """Return the persisted auxiliary record if it exists.

    Falls back to ``None`` when the file is missing or unreadable
    (first-ever run, the user has not yet collected auxiliary
    evidence).  The audit builder in that case produces a
    deterministic ``UNASSESSED`` record.
    """
    from scripts.verifiers_audit.report_io import (
        REPORT_ROOT,
    )
    path = REPORT_ROOT / "gate_classification.json"
    if not path.exists():
        return None
    import json as _json

    try:
        return _json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def cmd_write(
    gate_classification: dict[str, object] | None = None,
) -> int:
    """Build the audit object once, write every audit-owned shard
    and the markdown.

    Honours ``AUDIT01_SKIP_GATE=1`` for fast local sanity writes;
    production closures leave the env unset and rely on the
    real evidence.

    The persisted ``gate_classification.json`` is owned by
    :mod:`scripts.verifiers_audit.collect_r2_evidence` and is
    read here from disk only - never overwritten by the fast
    ``--write`` flow.  This is the ownership rule that prevents
    the fast report-generation flow from clobbering real
    auxiliary evidence.

    When ``--write`` is invoked without a previously-collected
    record on disk, the audit object carries a deterministic
    ``UNASSESSED`` record and the on-disk file is left absent.

    If ``gate_classification`` is supplied explicitly, the caller
    controls the in-memory record (used by unit tests to keep
    in-memory and on-disk byte-identical).  When the caller also
    asks for the shard to be persisted to disk, cmd_write will
    re-emit it so the in-memory and on-disk copies match.
    """
    # CORRECTION09: ``cmd_write`` MUST return nonzero and
    # perform zero side effects when a caller supplies a
    # non-None ``gate_classification`` argument.  This check
    # runs FIRST, before any shard write, before any
    # ``build_audit_object`` call, before any top-level write,
    # and before any markdown write.
    if gate_classification is not None:
        import sys as _sys

        print(
            "ERROR: cmd_write received a non-None "
            "gate_classification argument; per CORRECTION09 the "
            "canonical gate_classification writer is "
            "scripts/verifiers_audit.collect_r2_evidence, and "
            "audit.py --write is read-only for that shard.  "
            "The supplied record has been dropped and no "
            "artifact was written.  Exit code 2.",
            file=_sys.stderr,
        )
        return 2
    from scripts.verifiers_audit.report_io import _write_atomic

    skip_gate = os.environ.get("AUDIT01_SKIP_GATE") == "1"
    if gate_classification is None:
        gate_classification = _load_gate_classification_from_disk()
    audit = build_audit_object(
        {}, skip_gate=skip_gate, gate_classification=gate_classification
    )
    shards: dict[str, str] = {}
    hashes: dict[str, str] = {}
    for name in WRITE_OWNED_SHARDS:
        shard_path = REPORT_ROOT / f"{name}.json"
        body = _encode(name, audit[name])
        h = _write_atomic(shard_path, body)
        shards[name] = str(shard_path.relative_to(REPO_ROOT))
        hashes[name] = h
    if (REPORT_ROOT / "gate_classification.json").exists():
        # The on-disk file is authoritative; record its hash
        # in the in-memory index so cmd_check can validate it.
        # The shard is NOT re-written here.
        gc_path = REPORT_ROOT / "gate_classification.json"
        gc_bytes = gc_path.read_bytes()
        shards["gate_classification"] = str(
            gc_path.relative_to(REPO_ROOT)
        )
        hashes["gate_classification"] = hashlib.sha256(
            gc_bytes
        ).hexdigest()
    audit["index"]["shards"] = {
        name: {"path": p, "sha256": hashes[name]}
        for name, p in shards.items()
    }
    _write_atomic(TOP_LEVEL_JSON, _json_dumps(audit["index"]))
    MARKDOWN_PATH.write_bytes(render_markdown(audit).encode("utf-8"))
    for name in sorted(shards):
        print(f"wrote {name}: {shards[name]}")
    digest = _hash_bytes(_json_dumps(audit["index"]))
    print(f"index hash: {digest}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    grp = parser.add_mutually_exclusive_group(required=True)
    grp.add_argument("--check", action="store_true", help="Verify reports are up to date.")
    grp.add_argument("--write", action="store_true", help="Write reports.")
    args = parser.parse_args(argv)
    if args.check:
        return cmd_check()
    if args.write:
        return cmd_write()
    return 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
