# Content Index Module
#
# This module provides schema definitions and contracts for the k9b on-disk
# content index. The index accelerates UI/backend read paths by precomputing
# projections from source artifacts.

# Import freshness module
# Import readpath module (disabled-by-default index-backed read path)
from k8s_diag_agent.content_index.config import (
    CONTENT_INDEX_DB_PATH_ENV_VAR,
    CONTENT_INDEX_ENABLED_ENV_VAR,
    ContentIndexConfig,
    get_default_content_index_db_path,
    load_content_index_config_from_env,
)
from k8s_diag_agent.content_index.freshness import (
    HASH_CHUNK_SIZE,
    FingerprintResult,
    check_freshness,
    check_freshness_for_paths,
    check_schema_freshness,
    compute_sha256,
    fingerprint_file,
    fingerprint_file_from_content,
    summarize_freshness,
)

# Import indexer module (thin facade)
from k8s_diag_agent.content_index.indexer import (
    INDEX_PATTERNS,
    ContentIndexer,
    ContentIndexRoots,
    IndexerConfig,
    IndexerSummary,
    discover_sources,
    load_json_file,
    make_content_id,
    rebuild_index,
    update_index,
    validate_index,
)

# Import projections module (thin facade)
from k8s_diag_agent.content_index.projections import (
    ALLOWED_PROJECTION_FIELDS,
    CONTENT_KIND_PATTERNS,
    PROJECTION_API_DETAIL,
    PROJECTION_API_SUMMARY,
    ProjectionBuilder,
    ProjectionConfig,
    contains_forbidden_content,
    create_projections,
    detect_content_kind,
    project_generic,
    project_incident,
    project_lab_result,
    project_perf_baseline_summary,
    project_trace_capture_summary,
    strip_forbidden_fields,
    truncate_string,
    validate_projection_safety,
)
from k8s_diag_agent.content_index.readpath import (
    ContentIndexReader,
    FallbackReason,
    IndexReadResult,
    get_incident_from_index,
    list_incidents_from_index,
    record_fallback_span,
    record_success_span,
)

# Import schema module
from k8s_diag_agent.content_index.schema import (
    CONTENT_INDEX_SCHEMA_VERSION,
    FORBIDDEN_FIELD_PATTERNS,
    INDEXED_CONTENT_KINDS,
    INDEXED_PATH_KINDS,
    ContentIndexFreshness,
    ContentIndexRecord,
    ContentIndexValidationResult,
    ContentProjectionRecord,
    FreshnessStatus,
    check_forbidden_fields,
    get_content_kind_validator,
    validate_content_kind,
    validate_source_path,
)

# Import storage module (thin facade)
from k8s_diag_agent.content_index.storage import (
    atomically_replace_database,
    count_by_kind,
    count_items,
    create_content_index_temp_path,
    create_temp_database,
    delete_projection,
    get_all_content_items,
    get_connection,
    get_content_item,
    get_content_items_by_path_kind,
    get_metadata,
    get_projection,
    get_projections_for_item,
    get_schema_version,
    initialize_database,
    tombstone_content_item,
    update_indexed_at,
    upsert_content_item,
    upsert_projection,
    validate_database,
)

__all__ = [
    # Schema
    "CONTENT_INDEX_SCHEMA_VERSION",
    "INDEXED_CONTENT_KINDS",
    "INDEXED_PATH_KINDS",
    "ContentIndexRecord",
    "ContentIndexFreshness",
    "ContentIndexValidationResult",
    "ContentProjectionRecord",
    "FreshnessStatus",
    "get_content_kind_validator",
    "validate_content_kind",
    "validate_source_path",
    "check_forbidden_fields",
    "FORBIDDEN_FIELD_PATTERNS",
    # Storage
    "get_connection",
    "initialize_database",
    "create_temp_database",
    "create_content_index_temp_path",
    "get_metadata",
    "update_indexed_at",
    "get_schema_version",
    "upsert_content_item",
    "get_content_item",
    "get_all_content_items",
    "tombstone_content_item",
    "get_content_items_by_path_kind",
    "upsert_projection",
    "get_projection",
    "get_projections_for_item",
    "delete_projection",
    "validate_database",
    "atomically_replace_database",
    "count_items",
    "count_by_kind",
    # Freshness
    "FingerprintResult",
    "compute_sha256",
    "fingerprint_file",
    "fingerprint_file_from_content",
    "check_freshness",
    "check_schema_freshness",
    "check_freshness_for_paths",
    "summarize_freshness",
    "HASH_CHUNK_SIZE",
    # Projections
    "ALLOWED_PROJECTION_FIELDS",
    "PROJECTION_API_SUMMARY",
    "PROJECTION_API_DETAIL",
    "CONTENT_KIND_PATTERNS",
    "ProjectionConfig",
    "ProjectionBuilder",
    "detect_content_kind",
    "contains_forbidden_content",
    "strip_forbidden_fields",
    "truncate_string",
    "create_projections",
    "validate_projection_safety",
    "project_lab_result",
    "project_trace_capture_summary",
    "project_perf_baseline_summary",
    "project_incident",
    "project_generic",
    # Indexer
    "ContentIndexRoots",
    "IndexerConfig",
    "IndexerSummary",
    "INDEX_PATTERNS",
    "ContentIndexer",
    "discover_sources",
    "make_content_id",
    "load_json_file",
    "rebuild_index",
    "update_index",
    "validate_index",
    # Readpath (disabled-by-default index-backed read path)
    "ContentIndexConfig",
    "ContentIndexReader",
    "FallbackReason",
    "IndexReadResult",
    "CONTENT_INDEX_ENABLED_ENV_VAR",
    "CONTENT_INDEX_DB_PATH_ENV_VAR",
    "get_default_content_index_db_path",
    "load_content_index_config_from_env",
    "get_incident_from_index",
    "list_incidents_from_index",
    "record_fallback_span",
    "record_success_span",
]
