"""Internal incident review packet generator for k9b's own reviewer pipeline.

This module generates self-contained review packets from incident evidence bundles.
The packet is an internal k9b product artifact used by k9b's incident investigation
workflow - NOT a copy/paste artifact for external tools.

Hard constraint: End-state must be k9b-only and self-contained.
The complete incident investigation workflow must run inside k9b:
- no Cline required
- no manual kubectl required
- no operator exec into pods required
- no local CLI required
- no copy/paste to external tools required
- no external artifact massaging required

Development-time helpers are allowed, but every helper must either:
1. become an internal k9b backend/UI capability, or
2. be explicitly marked as temporary scaffolding and removed before the epic closes.
"""

from __future__ import annotations

from datetime import UTC
from typing import Any

from .incident_models import IncidentEvidenceBundle

# Self-contained k9b-only constraint text
K9B_SELF_CONTAINED_CONSTRAINT = """
## Self-Contained k9b-Only Constraint

This incident investigation workflow is designed to run entirely within k9b.

**NOT REQUIRED:**
- Cline or any external CLI tool
- Manual kubectl commands
- Operator shell access or pod exec
- Copy/paste to external tools
- Local scripts or external artifact conversion

**REQUIRED:**
- k9b backend for evidence capture
- k9b UI for review packet generation
- k9b reviewer pipeline for analysis

This packet contains structured evidence for k9b's internal reviewer pipeline.
"""

# Reviewer constraints text
REVIEWER_CONSTRAINTS = """
## Reviewer Constraints

CRITICAL: Follow these constraints when reviewing this packet:

1. **Evidence is NOT root cause**: This packet contains observed symptoms and
   derived signals. Do NOT treat evidence as proven root cause.

2. **Pod logs are NOT included**: This packet does NOT include pod container logs.
   To investigate logs, use k9b's diagnostic drilldown feature.

3. **Separate facts, hypotheses, and unknowns**:
   - Facts: directly observed signals (status, counts, events)
   - Hypotheses: reasoned interpretations requiring validation
   - Unknowns: missing evidence explicitly marked as such

4. **Do NOT invent missing evidence**: If evidence is insufficient to reach a
   conclusion, state what additional evidence would be needed.

5. **Ask for next evidence before proposing fixes**: When evidence is insufficient,
   recommend the next useful diagnostic check instead of proposing a fix.

6. **No autonomous diagnosis**: This system assists human review, not replaces it.
   All remediation recommendations require operator confirmation.
"""


def generate_incident_review_packet(
    bundle: IncidentEvidenceBundle,
) -> str:
    """Generate a deterministic, bounded, k9b-owned review packet.

    This packet is an internal product artifact used by k9b's incident
    investigation workflow, not a copy/paste artifact for external tools.

    Args:
        bundle: Incident evidence bundle from snapshot capture

    Returns:
        Markdown-formatted review packet

    Required packet contents:
    - metadata
    - evidence summary
    - detected symptoms
    - failing pods
    - deployment health
    - warning events
    - collection errors
    - known limitations
    - reviewer instructions
    - questions for next evidence collection
    - raw evidence index
    """
    lines: list[str] = []

    # Header
    lines.extend([
        "# k9b Incident Review Packet",
        "",
        "**Generated by k9b** - Self-contained incident investigation artifact",
        "",
        "---",
        "",
    ])

    # Metadata section
    lines.extend(_build_metadata_section(bundle))

    # Evidence summary section
    lines.extend(_build_evidence_summary(bundle))

    # Detected symptoms section
    lines.extend(_build_symptoms_section(bundle))

    # Failing pods section
    lines.extend(_build_failing_pods_section(bundle))

    # Deployment health section
    lines.extend(_build_deployment_health_section(bundle))

    # Warning events section
    lines.extend(_build_warning_events_section(bundle))

    # Collection errors section
    lines.extend(_build_collection_errors_section(bundle))

    # Known limitations section
    lines.extend(_build_known_limitations_section())

    # Raw evidence index
    lines.extend(_build_raw_evidence_index(bundle))

    # Self-contained constraint
    lines.extend([
        "---",
        "",
    ])
    lines.extend(K9B_SELF_CONTAINED_CONSTRAINT.split("\n"))

    # Reviewer constraints
    lines.extend([
        "",
        "---",
        "",
    ])
    lines.extend(REVIEWER_CONSTRAINTS.split("\n"))

    # Questions for next evidence collection
    lines.extend(_build_next_evidence_questions(bundle))

    return "\n".join(lines)


def _build_metadata_section(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build metadata section."""
    meta = bundle.metadata
    return [
        "## Metadata",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Bundle ID | `{meta.bundle_id}` |",
        f"| Captured At | {meta.captured_at.isoformat()} |",
        f"| Namespace | `{meta.namespace}` |",
        f"| Context | {meta.context or 'in-cluster (default)'} |",
        f"| Event Lookback | {meta.since_hours}h |",
        "",
    ]


def _build_evidence_summary(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build evidence summary section."""
    meta = bundle.metadata
    return [
        "## Evidence Summary",
        "",
        f"- **Total Pods**: {meta.total_pods}",
        f"- **Failing Pods**: {meta.failing_pods_count}",
        f"- **Total Deployments**: {meta.total_deployments}",
        f"- **Total Events**: {meta.total_events}",
        f"- **Detected Symptoms**: {meta.symptoms_count}",
        "",
    ]


def _build_symptoms_section(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build detected symptoms section."""
    lines = [
        "## Detected Symptoms",
        "",
    ]

    if not bundle.symptoms:
        lines.extend([
            "_No symptoms detected in captured evidence._",
            "",
        ])
    else:
        # Group by severity
        errors = [s for s in bundle.symptoms if s.severity == "error"]
        warnings = [s for s in bundle.symptoms if s.severity == "warning"]

        if errors:
            lines.append("### Critical (Error)")
            lines.append("")
            for symptom in errors:
                lines.append(f"- **{symptom.symptom_type}**")
                if symptom.pod_name:
                    lines.append(f"  - Pod: `{symptom.pod_name}`")
                lines.append(f"  - {symptom.message}")
                lines.append("")
        else:
            lines.append("### Critical (Error)")
            lines.append("")
            lines.append("_No critical symptoms detected._")
            lines.append("")

        if warnings:
            lines.append("### Warning")
            lines.append("")
            for symptom in warnings:
                lines.append(f"- **{symptom.symptom_type}**")
                if symptom.pod_name:
                    lines.append(f"  - Pod: `{symptom.pod_name}`")
                lines.append(f"  - {symptom.message}")
                lines.append("")
        else:
            lines.append("### Warning")
            lines.append("")
            lines.append("_No warning symptoms detected._")
            lines.append("")

    return lines


def _build_failing_pods_section(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build failing pods section."""
    lines = [
        "## Failing Pods",
        "",
    ]

    failing_pods = [p for p in bundle.pods if p.is_failing]

    if not failing_pods:
        lines.extend([
            "_No failing pods detected._",
            "",
        ])
    else:
        lines.append(f"Found {len(failing_pods)} failing pod(s):")
        lines.append("")
        lines.append("| Pod Name | Status | Restarts | Reason |")
        lines.append("|---------|--------|---------|-------|")
        for pod in failing_pods:
            lines.append(
                f"| `{pod.name}` | {pod.health_status.value} | "
                f"{pod.restart_count} | {pod.reason or '-'} |"
            )
        lines.append("")

    return lines


def _build_deployment_health_section(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build deployment health section."""
    lines = [
        "## Deployment Health",
        "",
    ]

    if not bundle.deployments:
        lines.extend([
            "_No deployments found in namespace._",
            "",
        ])
    else:
        lines.append("| Deployment | Replicas | Ready | Available |")
        lines.append("|------------|----------|-------|-----------|")
        for deploy in bundle.deployments:
            available = "✅" if deploy.available else "❌"
            lines.append(
                f"| `{deploy.name}` | {deploy.replicas} | "
                f"{deploy.ready_replicas}/{deploy.updated_replicas} | {available} |"
            )
        lines.append("")

        # Highlight unhealthy deployments
        unhealthy = [d for d in bundle.deployments if not d.available]
        if unhealthy:
            lines.extend([
                "**Unhealthy Deployments:**",
                "",
            ])
            for deploy in unhealthy:
                diff = deploy.replicas - deploy.available_replicas
                lines.append(
                    f"- `{deploy.name}`: {diff} replica(s) unavailable "
                    f"({deploy.ready_replicas}/{deploy.updated_replicas} ready)"
                )
            lines.append("")

    return lines


def _build_warning_events_section(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build warning events section."""
    lines = [
        "## Warning Events",
        "",
    ]

    warning_events = [e for e in bundle.events if e.type.lower() == "warning"]

    if not warning_events:
        lines.extend([
            "_No warning events in captured time window._",
            "",
        ])
    else:
        lines.append(f"{len(warning_events)} warning event(s) in captured time window:")
        lines.append("")
        lines.append("| Event | Reason | Involved Object | Count |")
        lines.append("|-------|--------|-----------------|-------|")
        for event in warning_events[:20]:  # Limit to 20 events
            involved = f"{event.involved_object_kind}:{event.involved_object_name}" if event.involved_object_name else "-"
            lines.append(
                f"| {event.name} | {event.reason} | {involved} | {event.count} |"
            )
        if len(warning_events) > 20:
            lines.append("")
            lines.append(f"_... and {len(warning_events) - 20} more events (truncated for packet size)_")
        lines.append("")

    return lines


def _build_collection_errors_section(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build collection errors section."""
    lines = [
        "## Collection Errors",
        "",
    ]

    if not bundle.collection_errors:
        lines.extend([
            "_No collection errors._",
            "",
        ])
    else:
        lines.append(f"{len(bundle.collection_errors)} error(s) during collection:")
        lines.append("")
        for error in bundle.collection_errors:
            lines.append(f"- {error}")
        lines.append("")
        lines.append("**Note:** Collection errors may indicate incomplete evidence. ")
        lines.append("Consider re-capturing or investigating the affected components.")
        lines.append("")

    return lines


def _build_known_limitations_section() -> list[str]:
    """Build known limitations section."""
    return [
        "## Known Limitations",
        "",
        "This packet captures a snapshot of cluster state at capture time. The following "
        "limitations apply:",
        "",
        "1. **Pod logs are NOT included**: Container logs are not part of this packet. "
        "Use k9b's diagnostic drilldown to capture pod logs.",
        "",
        "2. **Time-scoped evidence**: Events are filtered to the last 2 hours by default. "
        "Older events may contain relevant context but are not captured.",
        "",
        "3. **Namespace scope**: Only resources in the specified namespace are captured. "
        "Cross-namespace dependencies may not be visible.",
        "",
        "4. **Single context**: Collection targets one Kubernetes context (cluster). "
        "Multi-cluster correlation requires separate captures.",
        "",
        "5. **No historical comparison**: This packet shows current state. "
        "Historical drift detection requires baseline comparison.",
        "",
    ]


def _build_raw_evidence_index(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build raw evidence index section."""
    meta = bundle.metadata
    return [
        "## Raw Evidence Index",
        "",
        f"This packet references the following raw evidence from bundle `{meta.bundle_id}`:",
        "",
        f"- **Pods**: {meta.total_pods} pod summary record(s)",
        f"- **Deployments**: {meta.total_deployments} deployment summary record(s)",
        f"- **Events**: {meta.total_events} event summary record(s)",
        f"- **Symptoms**: {meta.symptoms_count} symptom detection record(s)",
        "",
        "The raw evidence is available in the incident bundle artifact for detailed inspection.",
        "",
    ]


def _build_next_evidence_questions(bundle: IncidentEvidenceBundle) -> list[str]:
    """Build questions for next evidence collection."""
    lines = [
        "---",
        "",
        "## Questions for Next Evidence Collection",
        "",
        "To continue the investigation, consider:",
        "",
    ]

    # Dynamic questions based on evidence
    if any(p.health_status.value == "crash_loop" for p in bundle.pods):
        lines.extend([
            "1. **CrashLoop investigation**: Capture container logs for the crashing pod",
            "   - Use k9b pod log drilldown to collect container logs",
        ])

    if any(p.health_status.value == "image_pull_error" for p in bundle.pods):
        lines.extend([
            "2. **Image pull investigation**: Check image pull configuration",
            "   - Use k9b to capture ImagePullSecrets on the namespace and pod",
        ])

    if any(p.health_status.value == "pending" for p in bundle.pods):
        lines.extend([
            "3. **Pending pod investigation**: Collect scheduler and node resource evidence:",
            "   - Use k9b pod describe evidence capture for scheduling events",
            "   - Use k9b node capacity evidence capture to verify resource availability",
        ])

    # Check for OOMKill indicators
    if any("oom" in e.reason.lower() or "oom" in e.message.lower() for e in bundle.events):
        lines.extend([
            "4. **Memory pressure investigation**: Check resource limits and node memory:",
            "   - Use k9b node detail evidence capture for memory pressure signals",
            "   - Use k9b to capture pod resource limits and requests",
        ])

    # Default questions if no specific patterns
    if len(lines) == 5:  # Only the static text
        lines.extend([
            "1. **Pod log capture**: Capture container logs for failing pods",
            "2. **Event timeline**: Check for warning events in adjacent namespaces",
            "3. **Node health**: Collect node-level evidence for scheduling issues",
        ])

    lines.append("")
    lines.append("**Remember**: Collect additional evidence before proposing remediation.")
    lines.append("")

    return lines


def generate_incident_review_packet_from_dict(
    bundle_data: dict[str, Any],
) -> str:
    """Generate review packet from bundle dict (for API responses).

    Args:
        bundle_data: Dictionary representation of IncidentEvidenceBundle

    Returns:
        Markdown-formatted review packet

    Raises:
        ValueError: If required bundle fields are missing
    """
    from .incident_models import (
        DeploymentSummary,
        EventSummary,
        IncidentBundleMetadata,
        IncidentEvidenceBundle,
        IncidentSymptom,
        PodSummary,
    )

    # Parse metadata
    meta_data = bundle_data.get("metadata", {})
    metadata = IncidentBundleMetadata(
        bundle_id=meta_data.get("bundle_id", ""),
        captured_at=_parse_datetime(meta_data.get("captured_at")),
        namespace=meta_data.get("namespace", ""),
        since_hours=meta_data.get("since_hours", 2),
        context=meta_data.get("context"),
        total_pods=meta_data.get("total_pods", 0),
        total_events=meta_data.get("total_events", 0),
        total_deployments=meta_data.get("total_deployments", 0),
        failing_pods_count=meta_data.get("failing_pods_count", 0),
        symptoms_count=meta_data.get("symptoms_count", 0),
    )

    # Parse pods
    from .incident_models import PodHealthStatus
    pods = []
    for pod_data in bundle_data.get("pods", []):
        health_status_str = pod_data.get("health_status", "unknown")
        if isinstance(health_status_str, str):
            try:
                health_status = PodHealthStatus(health_status_str)
            except ValueError:
                health_status = PodHealthStatus.UNKNOWN
        else:
            health_status = health_status_str
        pods.append(PodSummary(
            name=pod_data.get("name", ""),
            namespace=pod_data.get("namespace", ""),
            phase=pod_data.get("phase", ""),
            health_status=health_status,
            restart_count=pod_data.get("restart_count", 0),
            node=pod_data.get("node"),
            image_refs=tuple(pod_data.get("image_refs", [])),
            reason=pod_data.get("reason"),
            message=pod_data.get("message"),
            is_failing=pod_data.get("is_failing", False),
        ))

    # Parse events
    events = []
    for event_data in bundle_data.get("events", []):
        events.append(EventSummary(
            namespace=event_data.get("namespace", ""),
            name=event_data.get("name", ""),
            type=event_data.get("type", ""),
            reason=event_data.get("reason", ""),
            message=event_data.get("message", ""),
            involved_object_kind=event_data.get("involved_object_kind"),
            involved_object_name=event_data.get("involved_object_name"),
            count=event_data.get("count", 0),
            last_timestamp=event_data.get("last_timestamp"),
        ))

    # Parse deployments
    deployments = []
    for deploy_data in bundle_data.get("deployments", []):
        deployments.append(DeploymentSummary(
            name=deploy_data.get("name", ""),
            namespace=deploy_data.get("namespace", ""),
            replicas=deploy_data.get("replicas", 0),
            available_replicas=deploy_data.get("available_replicas", 0),
            ready_replicas=deploy_data.get("ready_replicas", 0),
            updated_replicas=deploy_data.get("updated_replicas", 0),
            available=deploy_data.get("available", False),
        ))

    # Parse symptoms
    symptoms = []
    for symptom_data in bundle_data.get("symptoms", []):
        symptoms.append(IncidentSymptom(
            symptom_type=symptom_data.get("symptom_type", ""),
            pod_name=symptom_data.get("pod_name"),
            message=symptom_data.get("message", ""),
            severity=symptom_data.get("severity", "warning"),
        ))

    # Parse collection errors
    collection_errors = tuple(bundle_data.get("collection_errors", []))

    # Build bundle
    bundle = IncidentEvidenceBundle(
        metadata=metadata,
        pods=pods,
        events=events,
        deployments=deployments,
        symptoms=symptoms,
        collection_errors=collection_errors,
    )

    return generate_incident_review_packet(bundle)


def _parse_datetime(value: str) -> Any:
    """Parse datetime string to datetime object."""
    from datetime import datetime
    if isinstance(value, datetime):
        return value
    # Try ISO format with timezone
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        pass
    # Try parsing without timezone and attach UTC
    try:
        # Handle "+00:00" suffix
        if '+' in value:
            base = value.split('+')[0]
            return datetime.fromisoformat(base).replace(tzinfo=UTC)
        return datetime.fromisoformat(value)
    except ValueError:
        return datetime.now(UTC)


__all__ = [
    "generate_incident_review_packet",
    "generate_incident_review_packet_from_dict",
    "K9B_SELF_CONTAINED_CONSTRAINT",
    "REVIEWER_CONSTRAINTS",
]
