"""Markdown rendering helpers for incident review packets.

This module contains pure markdown formatting and joining helpers.
"""

from __future__ import annotations

# Self-contained k9b-only constraint text
K9B_SELF_CONTAINED_CONSTRAINT = """
## Self-Contained k9b-Only Constraint

This incident investigation workflow is designed to run entirely within k9b.

**NOT REQUIRED:**
- Cline or any external CLI tool
- Manual kubectl commands
- Operator shell access or pod exec
- Copy/paste to external tools
- Local scripts or external artifact conversion

**REQUIRED:**
- k9b backend for evidence capture
- k9b UI for review packet generation
- k9b reviewer pipeline for analysis

This packet contains structured evidence for k9b's internal reviewer pipeline.
"""

# Reviewer constraints text
REVIEWER_CONSTRAINTS = """
## Reviewer Constraints

CRITICAL: Follow these constraints when reviewing this packet:

1. **Evidence is NOT root cause**: This packet contains observed symptoms and
   derived signals. Do NOT treat evidence as proven root cause.

2. **Pod logs are NOT included**: This packet does NOT include pod container logs.
   To investigate logs, use k9b's diagnostic drilldown feature.

3. **Separate facts, hypotheses, and unknowns**:
   - Facts: directly observed signals (status, counts, events)
   - Hypotheses: reasoned interpretations requiring validation
   - Unknowns: missing evidence explicitly marked as such

4. **Do NOT invent missing evidence**: If evidence is insufficient to reach a
   conclusion, state what additional evidence would be needed.

5. **Ask for next evidence before proposing fixes**: When evidence is insufficient,
   recommend the next useful diagnostic check instead of proposing a fix.

6. **No autonomous diagnosis**: This system assists human review, not replaces it.
   All remediation recommendations require operator confirmation.
"""


def build_header() -> list[str]:
    """Build the packet header."""
    return [
        "# k9b Incident Review Packet",
        "",
        "**Generated by k9b** - Self-contained incident investigation artifact",
        "",
        "---",
        "",
    ]


def build_constraint_sections() -> list[str]:
    """Build the constraint sections (self-contained and reviewer constraints)."""
    lines = [
        "---",
        "",
    ]
    lines.extend(K9B_SELF_CONTAINED_CONSTRAINT.split("\n"))
    lines.extend([
        "",
        "---",
        "",
    ])
    lines.extend(REVIEWER_CONSTRAINTS.split("\n"))
    return lines


def join_lines(sections: list[list[str]]) -> str:
    """Join multiple sections of lines into a single markdown string."""
    lines: list[str] = []
    for section in sections:
        lines.extend(section)
    return "\n".join(lines)


__all__ = [
    "K9B_SELF_CONTAINED_CONSTRAINT",
    "REVIEWER_CONSTRAINTS",
    "build_header",
    "build_constraint_sections",
    "join_lines",
]
