"""vmalert HTTP client for fetching alert/rule state.

This module provides read-only access to vmalert's alerting state via its HTTP API.
vmalert is the primary alert/rule source for VictoriaMetrics stack clusters that
do not use Alertmanager.

Key invariants:
- Never raises for normal network/API failures (non-fatal to health loop)
- Uses short timeouts
- Returns typed/structured results suitable for downstream processing
- Does not depend on Alertmanager

API surface:
- /api/v1/rules - Rule groups, rules, and their states
- /api/v1/alerts - Active alerts generated by vmalert
"""

from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

# Module logger
_logger = logging.getLogger(__name__)

# Default timeout for vmalert API requests
DEFAULT_TIMEOUT_SECONDS = 5.0


class VmalertFetchStatus(StrEnum):
    """Status of a vmalert fetch operation."""

    OK = "ok"
    EMPTY = "empty"
    TIMEOUT = "timeout"
    UPSTREAM_ERROR = "upstream_error"
    INVALID_RESPONSE = "invalid_response"
    FETCH_ERROR = "fetch_error"


@dataclass(frozen=True)
class VmalertFetchResult:
    """Result of fetching alert/rule state from a vmalert endpoint."""

    status: VmalertFetchStatus
    source_endpoint: str
    captured_at: str
    raw_response: dict[str, Any] | None = None
    error: str | None = None
    fetch_duration_ms: int | None = None

    @property
    def is_ok(self) -> bool:
        """Return True if the fetch was successful."""
        return self.status in (VmalertFetchStatus.OK, VmalertFetchStatus.EMPTY)


def fetch_vmalert_rules(endpoint: str, timeout: float = DEFAULT_TIMEOUT_SECONDS) -> VmalertFetchResult:
    """Fetch rule groups and rule state from vmalert's /api/v1/rules endpoint.

    This endpoint returns:
    - rule_groups[]: each containing name, file, interval
    - rules[] within each group: id, name, type, health, last_error, alerts

    Args:
        endpoint: Base URL of the vmalert instance (e.g., "http://vmalert.ns:8080")
        timeout: Request timeout in seconds

    Returns:
        VmalertFetchResult with status and raw response data
    """
    start_time = datetime.now(UTC)
    url = f"{endpoint.rstrip('/')}/api/v1/rules"

    try:
        req = urllib.request.Request(url, headers={"Accept": "application/json"})
        with urllib.request.urlopen(req, timeout=timeout) as response:
            body = response.read()
            try:
                data: dict[str, Any] = json.loads(body)
            except json.JSONDecodeError as exc:
                return VmalertFetchResult(
                    status=VmalertFetchStatus.INVALID_RESPONSE,
                    source_endpoint=endpoint,
                    captured_at=datetime.now(UTC).isoformat(),
                    error=f"Invalid JSON response: {exc}",
                    fetch_duration_ms=_duration_ms(start_time),
                )

            # Check for vmalert error response
            if data.get("error"):
                return VmalertFetchResult(
                    status=VmalertFetchStatus.UPSTREAM_ERROR,
                    source_endpoint=endpoint,
                    captured_at=datetime.now(UTC).isoformat(),
                    raw_response=data,
                    error=str(data.get("error", "Unknown vmalert error")),
                    fetch_duration_ms=_duration_ms(start_time),
                )

            return VmalertFetchResult(
                status=VmalertFetchStatus.OK,
                source_endpoint=endpoint,
                captured_at=datetime.now(UTC).isoformat(),
                raw_response=data,
                fetch_duration_ms=_duration_ms(start_time),
            )

    except urllib.error.HTTPError as exc:
        return VmalertFetchResult(
            status=VmalertFetchStatus.UPSTREAM_ERROR,
            source_endpoint=endpoint,
            captured_at=datetime.now(UTC).isoformat(),
            error=f"HTTP {exc.code}: {exc.reason}",
            fetch_duration_ms=_duration_ms(start_time),
        )
    except urllib.error.URLError as exc:
        return VmalertFetchResult(
            status=VmalertFetchStatus.FETCH_ERROR,
            source_endpoint=endpoint,
            captured_at=datetime.now(UTC).isoformat(),
            error=f"Connection failed: {exc.reason}",
            fetch_duration_ms=_duration_ms(start_time),
        )
    except TimeoutError:
        return VmalertFetchResult(
            status=VmalertFetchStatus.TIMEOUT,
            source_endpoint=endpoint,
            captured_at=datetime.now(UTC).isoformat(),
            error="Request timed out",
            fetch_duration_ms=_duration_ms(start_time),
        )


def fetch_vmalert_alerts(endpoint: str, timeout: float = DEFAULT_TIMEOUT_SECONDS) -> VmalertFetchResult:
    """Fetch active alerts from vmalert's /api/v1/alerts endpoint.

    This endpoint returns alerts currently firing or pending:
    - alerts[]: name, expr, type, state, labels, annotations, active_at, value

    Args:
        endpoint: Base URL of the vmalert instance
        timeout: Request timeout in seconds

    Returns:
        VmalertFetchResult with status and raw response data
    """
    start_time = datetime.now(UTC)
    url = f"{endpoint.rstrip('/')}/api/v1/alerts"

    try:
        req = urllib.request.Request(url, headers={"Accept": "application/json"})
        with urllib.request.urlopen(req, timeout=timeout) as response:
            body = response.read()
            try:
                data: dict[str, Any] = json.loads(body)
            except json.JSONDecodeError as exc:
                return VmalertFetchResult(
                    status=VmalertFetchStatus.INVALID_RESPONSE,
                    source_endpoint=endpoint,
                    captured_at=datetime.now(UTC).isoformat(),
                    error=f"Invalid JSON response: {exc}",
                    fetch_duration_ms=_duration_ms(start_time),
                )

            # Check for vmalert error response
            if data.get("error"):
                return VmalertFetchResult(
                    status=VmalertFetchStatus.UPSTREAM_ERROR,
                    source_endpoint=endpoint,
                    captured_at=datetime.now(UTC).isoformat(),
                    raw_response=data,
                    error=str(data.get("error", "Unknown vmalert error")),
                    fetch_duration_ms=_duration_ms(start_time),
                )

            return VmalertFetchResult(
                status=VmalertFetchStatus.OK,
                source_endpoint=endpoint,
                captured_at=datetime.now(UTC).isoformat(),
                raw_response=data,
                fetch_duration_ms=_duration_ms(start_time),
            )

    except urllib.error.HTTPError as exc:
        return VmalertFetchResult(
            status=VmalertFetchStatus.UPSTREAM_ERROR,
            source_endpoint=endpoint,
            captured_at=datetime.now(UTC).isoformat(),
            error=f"HTTP {exc.code}: {exc.reason}",
            fetch_duration_ms=_duration_ms(start_time),
        )
    except urllib.error.URLError as exc:
        return VmalertFetchResult(
            status=VmalertFetchStatus.FETCH_ERROR,
            source_endpoint=endpoint,
            captured_at=datetime.now(UTC).isoformat(),
            error=f"Connection failed: {exc.reason}",
            fetch_duration_ms=_duration_ms(start_time),
        )
    except TimeoutError:
        return VmalertFetchResult(
            status=VmalertFetchStatus.TIMEOUT,
            source_endpoint=endpoint,
            captured_at=datetime.now(UTC).isoformat(),
            error="Request timed out",
            fetch_duration_ms=_duration_ms(start_time),
        )


def _duration_ms(start_time: datetime) -> int:
    """Calculate duration in milliseconds since start_time."""
    delta = datetime.now(UTC) - start_time
    return int(delta.total_seconds() * 1000)