"""Unit tests for adaptation provenance in incident report.

Generated by split.
"""

from __future__ import annotations

import unittest

from k8s_diag_agent.ui.api_incident_report import (
    _build_operator_worklist_payload,
)
from k8s_diag_agent.ui.model import build_ui_context
from tests.fixtures.incident_report_fixtures import (
    _fixture_degraded_single_cluster,
)


class AdaptationProvenanceTests(unittest.TestCase):
    """Tests for feedback adaptation provenance on executed/reviewed worklist items.

    Coverage goals:
    - adaptation provenance present when feedback exists
    - no material-change represented honestly
    - feedback doesn't silently rewrite facts
    - usefulness labels and adaptation effects consistent
    - executed items explain changes without pretending certainty
    """

    def setUp(self) -> None:
        # Import new fixtures
        from tests.fixtures.incident_report_fixtures import (
            _fixture_executed_result_deprioritizes_action,
            _fixture_executed_result_promotes_action,
            _fixture_noisy_result_no_material_change,
            _fixture_partial_result_unknown_resolved,
            _fixture_useful_result_hypothesis_strengthened,
        )
        self._fixture_useful = _fixture_useful_result_hypothesis_strengthened
        self._fixture_noisy = _fixture_noisy_result_no_material_change
        self._fixture_partial = _fixture_partial_result_unknown_resolved
        self._fixture_promote = _fixture_executed_result_promotes_action
        self._fixture_deprioritize = _fixture_executed_result_deprioritizes_action

    def test_useful_result_has_hypothesis_strengthened_provenance(self) -> None:
        """Useful feedback produces hypothesis_strengthened adaptation effect."""
        index = self._fixture_useful()
        context = build_ui_context(index)
        worklist = _build_operator_worklist_payload(context)
        self.assertIsNotNone(worklist)
        assert worklist is not None

        # Find executed item with usefulness feedback
        executed_items = [
            i for i in worklist["items"]
            if i.get("itemState") in ("executed", "reviewed")
            and i.get("executionState") in ("executed-success", "completed")
        ]
        self.assertTrue(executed_items, "Expected at least one executed item")

        item = executed_items[0]
        provenance = item.get("feedbackAdaptationProvenance")

        # Provenance must be present for executed items with feedback
        self.assertIsNotNone(provenance, "feedbackAdaptationProvenance must be present")
        assert provenance is not None

        # Verify adaptation effect matches usefulness class
        self.assertEqual(provenance.get("adaptationEffect"), "hypothesis_strengthened")
        self.assertEqual(provenance.get("feedbackAdaptation"), True)
        self.assertIn("adaptationReason", provenance)
        self.assertIn("adaptationSummary", provenance)
        self.assertIn("explanation", provenance)

    def test_noisy_result_has_no_material_change_provenance(self) -> None:
        """Noisy feedback produces no_material_change adaptation effect."""
        index = self._fixture_noisy()
        context = build_ui_context(index)
        worklist = _build_operator_worklist_payload(context)
        self.assertIsNotNone(worklist)
        assert worklist is not None

        # Find executed item with noisy usefulness
        noisy_items = [
            i for i in worklist["items"]
            if i.get("executionState") in ("executed-success", "completed")
            and i.get("feedbackAdaptationProvenance") is not None
        ]
        self.assertTrue(noisy_items, "Expected at least one executed item with provenance")

        item = noisy_items[0]
        provenance = item.get("feedbackAdaptationProvenance")
        assert provenance is not None

        # Noisy feedback must result in no_material_change
        self.assertEqual(provenance.get("adaptationEffect"), "no_material_change")

        # Adaptation summary must honestly represent no diagnostic impact
        summary = provenance.get("adaptationSummary", "")
        self.assertTrue(
            "no material" in str(summary).lower() or "no change" in str(summary).lower(),
            f"Expected honest 'no material change' summary, got: {summary}",
        )

    def test_partial_result_has_unknown_resolved_provenance(self) -> None:
        """Partial feedback produces unknown_resolved adaptation effect."""
        index = self._fixture_partial()
        context = build_ui_context(index)
        worklist = _build_operator_worklist_payload(context)
        self.assertIsNotNone(worklist)
        assert worklist is not None

        # Find executed item with partial usefulness
        partial_items = [
            i for i in worklist["items"]
            if i.get("executionState") in ("executed-success", "completed")
            and i.get("feedbackAdaptationProvenance") is not None
        ]
        self.assertTrue(partial_items, "Expected at least one executed item with provenance")

        item = partial_items[0]
        provenance = item.get("feedbackAdaptationProvenance")
        assert provenance is not None

        # Partial feedback must result in unknown_resolved
        self.assertEqual(provenance.get("adaptationEffect"), "unknown_resolved")

        # Adaptation summary should mention resolution
        summary = provenance.get("adaptationSummary", "")
        self.assertTrue(
            "resolved" in str(summary).lower() or "evidence" in str(summary).lower(),
            f"Expected resolution mention in summary, got: {summary}",
        )

    def test_useful_feedback_promotes_action(self) -> None:
        """Useful feedback that surfaces new action has recommendation_promoted effect."""
        index = self._fixture_promote()
        context = build_ui_context(index)
        worklist = _build_operator_worklist_payload(context)
        self.assertIsNotNone(worklist)
        assert worklist is not None

        # Find executed item with useful feedback
        useful_items = [
            i for i in worklist["items"]
            if i.get("executionState") in ("executed-success", "completed")
            and i.get("feedbackAdaptationProvenance") is not None
        ]
        self.assertTrue(useful_items, "Expected at least one executed item with provenance")

        item = useful_items[0]
        provenance = item.get("feedbackAdaptationProvenance")
        assert provenance is not None

        # Verify adaptation effect is hypothesis_strengthened (useful result)
        self.assertEqual(
            provenance.get("adaptationEffect"),
            "hypothesis_strengthened",
            "Useful result should strengthen hypothesis",
        )

        # Verify the pending item exists (action promotion scenario)
        pending_items = [
            i for i in worklist["items"]
            if i.get("executionState") == "unexecuted"
        ]
        self.assertTrue(pending_items, "Expected pending items for action promotion")

    def test_deprioritization_has_recommendation_deprioritized_effect(self) -> None:
        """Noisy feedback that downgrades prior action has recommendation_deprioritized effect."""
        index = self._fixture_deprioritize()
        context = build_ui_context(index)
        worklist = _build_operator_worklist_payload(context)
        self.assertIsNotNone(worklist)
        assert worklist is not None

        # Find executed item with noisy feedback
        noisy_items = [
            i for i in worklist["items"]
            if i.get("executionState") in ("executed-success", "completed")
            and i.get("feedbackAdaptationProvenance") is not None
        ]
        self.assertTrue(noisy_items, "Expected at least one executed item with provenance")

        item = noisy_items[0]
        provenance = item.get("feedbackAdaptationProvenance")
        assert provenance is not None

        # Noisy feedback must result in no_material_change (deprioritization signal)
        self.assertEqual(provenance.get("adaptationEffect"), "no_material_change")

    def test_no_feedback_no_provenance(self) -> None:
        """Items without usefulness feedback have no adaptation provenance."""
        index = _fixture_degraded_single_cluster()
        context = build_ui_context(index)
        worklist = _build_operator_worklist_payload(context)
        self.assertIsNotNone(worklist)
        assert worklist is not None

        # Items without execution feedback should not have adaptation provenance
        for item in worklist["items"]:
            if not item.get("executionState"):
                self.assertIsNone(
                    item.get("feedbackAdaptationProvenance"),
                    f"Unexecuted item should not have adaptation provenance: {item.get('id')}",
                )

    def test_adaptation_effect_constants_are_correct(self) -> None:
        """Verify adaptation effect constants match the taxonomy."""
        from k8s_diag_agent.ui.api_incident_report import (
            _ADAPTATION_EFFECT_HYPOTHESIS_STRENGTHENED,
            _ADAPTATION_EFFECT_HYPOTHESIS_WEAKENED,
            _ADAPTATION_EFFECT_NO_MATERIAL_CHANGE,
            _ADAPTATION_EFFECT_RECOMMENDATION_DEPRIORITIZED,
            _ADAPTATION_EFFECT_RECOMMENDATION_PROMOTED,
            _ADAPTATION_EFFECT_UNKNOWN_RESOLVED,
            _USE_TO_ADAPTATION_MAP,
        )

        # Verify all expected effects exist
        self.assertEqual(_ADAPTATION_EFFECT_HYPOTHESIS_STRENGTHENED, "hypothesis_strengthened")
        self.assertEqual(_ADAPTATION_EFFECT_HYPOTHESIS_WEAKENED, "hypothesis_weakened")
        self.assertEqual(_ADAPTATION_EFFECT_UNKNOWN_RESOLVED, "unknown_resolved")
        self.assertEqual(_ADAPTATION_EFFECT_RECOMMENDATION_PROMOTED, "recommendation_promoted")
        self.assertEqual(_ADAPTATION_EFFECT_RECOMMENDATION_DEPRIORITIZED, "recommendation_deprioritized")
        self.assertEqual(_ADAPTATION_EFFECT_NO_MATERIAL_CHANGE, "no_material_change")

        # Verify mapping from usefulness class to effect
        self.assertEqual(_USE_TO_ADAPTATION_MAP.get("useful"), "hypothesis_strengthened")
        self.assertEqual(_USE_TO_ADAPTATION_MAP.get("partial"), "unknown_resolved")
        self.assertEqual(_USE_TO_ADAPTATION_MAP.get("noisy"), "no_material_change")
        self.assertEqual(_USE_TO_ADAPTATION_MAP.get("empty"), "no_material_change")

    def test_feedback_provenance_fields_complete(self) -> None:
        """Adaptation provenance dict contains all required fields."""
        index = self._fixture_useful()
        context = build_ui_context(index)
        worklist = _build_operator_worklist_payload(context)
        self.assertIsNotNone(worklist)
        assert worklist is not None

        # Find item with provenance
        provenance_items = [
            i for i in worklist["items"]
            if i.get("feedbackAdaptationProvenance") is not None
        ]
        self.assertTrue(provenance_items, "Expected at least one item with provenance")

        provenance = provenance_items[0].get("feedbackAdaptationProvenance")
        assert provenance is not None

        # Verify all required provenance fields
        required_fields = [
            "feedbackAdaptation",
            "adaptationReason",
            "adaptationEffect",
            "adaptationSummary",
            "originalBonus",
            "suppressedBonus",
            "penaltyApplied",
            "explanation",
        ]
        for field in required_fields:
            self.assertIn(field, provenance, f"Required field '{field}' missing from provenance")

    def test_executed_items_retain_provenance_after_projection(self) -> None:
        """Executed items preserve adaptation provenance through worklist projection."""
        index = self._fixture_useful()
        context = build_ui_context(index)
        worklist = _build_operator_worklist_payload(context)
        self.assertIsNotNone(worklist)
        assert worklist is not None

        # Verify executed items have provenance
        executed_with_provenance = [
            i for i in worklist["items"]
            if i.get("itemState") in ("executed", "reviewed")
            and i.get("feedbackAdaptationProvenance") is not None
        ]
        self.assertTrue(
            executed_with_provenance,
            "Executed items must have adaptation provenance",
        )

    def test_derive_adaptation_provenance_function(self) -> None:
        """Test the _derive_adaptation_provenance function directly."""
        from k8s_diag_agent.ui.api_incident_report import _derive_adaptation_provenance

        # Test useful feedback
        result = _derive_adaptation_provenance(
            usefulness_class="useful",
            usefulness_summary="Found crash events confirming hypothesis",
            execution_result_summary="Captured pod events showing crash pattern",
        )
        self.assertIsNotNone(result)
        assert result is not None
        self.assertEqual(result["adaptationEffect"], "hypothesis_strengthened")
        self.assertEqual(result["feedbackAdaptation"], True)
        summary = str(result["adaptationSummary"] or "")
        self.assertIn("Strengthened", summary)

        # Test noisy feedback
        result = _derive_adaptation_provenance(
            usefulness_class="noisy",
            usefulness_summary="Logs contained only routine messages",
            execution_result_summary="No crash details captured",
        )
        self.assertIsNotNone(result)
        assert result is not None
        self.assertEqual(result["adaptationEffect"], "no_material_change")
        self.assertIn("no material", result["adaptationSummary"].lower())

        # Test partial feedback
        result = _derive_adaptation_provenance(
            usefulness_class="partial",
            usefulness_summary="Found events but exit code missing",
            execution_result_summary="Partial events captured",
        )
        self.assertIsNotNone(result)
        assert result is not None
        self.assertEqual(result["adaptationEffect"], "unknown_resolved")

        # Test empty usefulness class returns None
        result = _derive_adaptation_provenance(
            usefulness_class=None,
            usefulness_summary=None,
            execution_result_summary=None,
        )
        self.assertIsNone(result)

        # Test unknown usefulness class returns None
        result = _derive_adaptation_provenance(
            usefulness_class="unknown",
            usefulness_summary="Something",
            execution_result_summary="Something",
        )
        self.assertIsNone(result)


# =============================================================================
# Temporal Context Regression Tests (Epic: BETA-G4 Temporal Context in Worklist)
# =============================================================================


