"""Unit tests for vmalert discovery context in incident report.

Generated by split.
"""

from __future__ import annotations

import unittest
from typing import cast

from k8s_diag_agent.ui.api import build_run_payload
from k8s_diag_agent.ui.api_incident_report import (
    _build_incident_report_payload,
)
from k8s_diag_agent.ui.model import build_ui_context
from tests.fixtures.ui_index_sample import sample_ui_index
from tests.unit.test_api_incident_report_helpers import _sample_freshness


class VmalertDiscoveryContextTests(unittest.TestCase):
    """Tests for vmalert discovery context in incident report."""

    def test_incident_report_includes_vmalert_context_when_sources_exist(self) -> None:
        """Test that incident report includes vmalertDiscoveryContext when vmalert sources are present."""
        index = sample_ui_index()
        # Add vmalert sources to the run data
        run_entry = cast(dict[str, object], index["run"])
        run_entry["vmalert_sources"] = {
            "sources": [
                {
                    "source_id": "test-vmalert-1",
                    "endpoint": "http://vmalert:8880",
                    "namespace": "victoria-metrics",
                    "name": "vmalert",
                    "origin": "service-heuristic",
                    "state": "discovered",
                    "discovered_at": "2026-01-01T00:00:00Z",
                    "verified_at": None,
                    "last_check": None,
                    "last_error": None,
                    "verified_version": None,
                    "confidence_hints": ["vmalert-name-matched"],
                    "merged_provenances": ["service-heuristic"],
                    "display_provenance": "Service Heuristic",
                    "is_manual": False,
                    "is_tracking": False,
                    "can_disable": False,
                    "can_promote": True,
                    "display_origin": "Service Heuristic",
                    "display_state": "Discovered",
                    "provenance_summary": "vmalert-name-matched",
                    "cluster_label": "cluster-a",
                    "manual_source_mode": None,
                    "canonicalEntityId": None,
                    "cluster_uid": None,
                    "object_uid": None,
                }
            ],
            "total_count": 1,
            "source_count": 1,
            "discovered_count": 1,
            "discovered_but_unverified_count": 0,
            "auto_tracked_count": 0,
            "manual_count": 0,
            "discovery_timestamp": "2026-01-01T00:00:00Z",
            "cluster_context": "cluster-a",
        }
        context = build_ui_context(index)
        payload = _build_incident_report_payload(context, _sample_freshness("fresh"))
        self.assertIsNotNone(payload)
        assert payload is not None
        # vmalert context should be present
        self.assertIn("vmalertDiscoveryContext", payload)
        vmalert_ctx = payload["vmalertDiscoveryContext"]
        self.assertIsNotNone(vmalert_ctx)
        assert vmalert_ctx is not None
        # Verify source count
        self.assertEqual(vmalert_ctx["source_count"], 1)
        self.assertEqual(vmalert_ctx["discovered_count"], 1)
        self.assertEqual(vmalert_ctx["discovered_but_unverified_count"], 0)
        # Verify source details
        self.assertEqual(len(vmalert_ctx["sources"]), 1)
        source = vmalert_ctx["sources"][0]
        self.assertEqual(source["endpoint"], "http://vmalert:8880")
        self.assertEqual(source["namespace"], "victoria-metrics")
        self.assertEqual(source["name"], "vmalert")
        self.assertEqual(source["origin"], "service-heuristic")
        self.assertEqual(source["state"], "discovered")
        self.assertEqual(source["display_provenance"], "Service Heuristic")
        self.assertEqual(source["cluster_label"], "cluster-a")

    def test_incident_report_includes_discovered_but_unverified_sources(self) -> None:
        """Test that discovered-but-unverified sources are represented but non-fatal."""
        index = sample_ui_index()
        run_entry = cast(dict[str, object], index["run"])
        run_entry["vmalert_sources"] = {
            "sources": [
                {
                    "source_id": "test-vmalert-unverified",
                    "endpoint": "http://vmalert-unverified:8880",
                    "namespace": "victoria-metrics",
                    "name": "vmalert-unverified",
                    "origin": "service-heuristic",
                    "state": "discovered-but-unverified",
                    "discovered_at": "2026-01-01T00:00:00Z",
                    "verified_at": None,
                    "last_check": None,
                    "last_error": "Connection refused",
                    "verified_version": None,
                    "confidence_hints": [],
                    "merged_provenances": ["service-heuristic"],
                    "display_provenance": "Service Heuristic",
                    "is_manual": False,
                    "is_tracking": False,
                    "can_disable": False,
                    "can_promote": True,
                    "display_origin": "Service Heuristic",
                    "display_state": "Discovered (Unverified)",
                    "provenance_summary": "-",
                    "cluster_label": "cluster-a",
                    "manual_source_mode": None,
                    "canonicalEntityId": None,
                    "cluster_uid": None,
                    "object_uid": None,
                }
            ],
            "total_count": 1,
            "source_count": 1,
            "discovered_count": 0,
            "discovered_but_unverified_count": 1,
            "auto_tracked_count": 0,
            "manual_count": 0,
            "discovery_timestamp": "2026-01-01T00:00:00Z",
            "cluster_context": "cluster-a",
        }
        context = build_ui_context(index)
        payload = _build_incident_report_payload(context, _sample_freshness("fresh"))
        self.assertIsNotNone(payload)
        assert payload is not None
        # vmalert context should be present
        self.assertIn("vmalertDiscoveryContext", payload)
        vmalert_ctx = payload["vmalertDiscoveryContext"]
        self.assertIsNotNone(vmalert_ctx)
        assert vmalert_ctx is not None
        # Verify counts reflect unverified state
        self.assertEqual(vmalert_ctx["source_count"], 1)
        self.assertEqual(vmalert_ctx["discovered_count"], 0)
        self.assertEqual(vmalert_ctx["discovered_but_unverified_count"], 1)
        # State should be preserved
        source = vmalert_ctx["sources"][0]
        self.assertEqual(source["state"], "discovered-but-unverified")

    def test_incident_report_null_vmalert_when_no_sources(self) -> None:
        """Test that incident report has null vmalert context when no vmalert sources."""
        # Create index without vmalert sources
        index = sample_ui_index()
        # Ensure no vmalert_sources in run
        run_entry = cast(dict[str, object], index["run"])
        if "vmalert_sources" in run_entry:
            del run_entry["vmalert_sources"]
        context = build_ui_context(index)
        payload = _build_incident_report_payload(context, _sample_freshness("fresh"))
        self.assertIsNotNone(payload)
        assert payload is not None
        # vmalert context should be None when no sources
        self.assertIn("vmalertDiscoveryContext", payload)
        self.assertIsNone(payload["vmalertDiscoveryContext"])

    def test_vmalert_context_quiet_when_source_count_zero(self) -> None:
        """Test that zero vmalert sources is quiet (not an error)."""
        index = sample_ui_index()
        run_entry = cast(dict[str, object], index["run"])
        # Empty sources - not an error
        run_entry["vmalert_sources"] = {
            "sources": [],
            "total_count": 0,
            "source_count": 0,
            "discovered_count": 0,
            "discovered_but_unverified_count": 0,
            "auto_tracked_count": 0,
            "manual_count": 0,
            "discovery_timestamp": None,
            "cluster_context": None,
        }
        context = build_ui_context(index)
        payload = _build_incident_report_payload(context, _sample_freshness("fresh"))
        self.assertIsNotNone(payload)
        assert payload is not None
        # vmalert context should be present but with zero counts
        self.assertIn("vmalertDiscoveryContext", payload)
        vmalert_ctx = payload["vmalertDiscoveryContext"]
        self.assertIsNotNone(vmalert_ctx)
        assert vmalert_ctx is not None
        self.assertEqual(vmalert_ctx["source_count"], 0)
        self.assertEqual(len(vmalert_ctx["sources"]), 0)

    def test_vmalert_context_multiple_sources(self) -> None:
        """Test vmalert context with multiple sources."""
        index = sample_ui_index()
        run_entry = cast(dict[str, object], index["run"])
        run_entry["vmalert_sources"] = {
            "sources": [
                {
                    "source_id": "test-vmalert-1",
                    "endpoint": "http://vmalert-1:8880",
                    "namespace": "vm-ns-1",
                    "name": "vmalert-1",
                    "origin": "vmalert-crd",
                    "state": "auto-tracked",
                    "discovered_at": "2026-01-01T00:00:00Z",
                    "verified_at": "2026-01-01T00:01:00Z",
                    "last_check": "2026-01-01T00:01:00Z",
                    "last_error": None,
                    "verified_version": "vmalert-2024.1.0",
                    "confidence_hints": ["crd-matched", "http-verified"],
                    "merged_provenances": ["vmalert-crd"],
                    "display_provenance": "VMAlert CRD",
                    "is_manual": False,
                    "is_tracking": True,
                    "can_disable": True,
                    "can_promote": False,
                    "display_origin": "VMAlert CRD",
                    "display_state": "Auto-tracked",
                    "provenance_summary": "crd-matched; http-verified",
                    "cluster_label": "cluster-a",
                    "manual_source_mode": None,
                    "canonicalEntityId": "hash-123",
                    "cluster_uid": "uid-abc",
                    "object_uid": "obj-def",
                },
                {
                    "source_id": "test-vmalert-2",
                    "endpoint": "http://vmalert-2:8880",
                    "namespace": "vm-ns-2",
                    "name": "vmalert-2",
                    "origin": "service-heuristic",
                    "state": "discovered",
                    "discovered_at": "2026-01-01T00:00:00Z",
                    "verified_at": None,
                    "last_check": None,
                    "last_error": None,
                    "verified_version": None,
                    "confidence_hints": ["vmalert-name-matched"],
                    "merged_provenances": ["service-heuristic"],
                    "display_provenance": "Service Heuristic",
                    "is_manual": False,
                    "is_tracking": False,
                    "can_disable": False,
                    "can_promote": True,
                    "display_origin": "Service Heuristic",
                    "display_state": "Discovered",
                    "provenance_summary": "vmalert-name-matched",
                    "cluster_label": "cluster-b",
                    "manual_source_mode": None,
                    "canonicalEntityId": "hash-456",
                    "cluster_uid": None,
                    "object_uid": None,
                },
            ],
            "total_count": 2,
            "source_count": 2,
            "discovered_count": 1,
            "discovered_but_unverified_count": 0,
            "auto_tracked_count": 1,
            "manual_count": 0,
            "discovery_timestamp": "2026-01-01T00:00:00Z",
            "cluster_context": "cluster-a",
        }
        context = build_ui_context(index)
        payload = _build_incident_report_payload(context, _sample_freshness("fresh"))
        self.assertIsNotNone(payload)
        assert payload is not None
        vmalert_ctx = payload["vmalertDiscoveryContext"]
        self.assertIsNotNone(vmalert_ctx)
        assert vmalert_ctx is not None
        # Verify counts
        self.assertEqual(vmalert_ctx["source_count"], 2)
        self.assertEqual(vmalert_ctx["discovered_count"], 1)
        self.assertEqual(len(vmalert_ctx["sources"]), 2)
        # Verify both sources are present
        endpoints = {s["endpoint"] for s in vmalert_ctx["sources"]}
        self.assertIn("http://vmalert-1:8880", endpoints)
        self.assertIn("http://vmalert-2:8880", endpoints)

    def test_run_payload_includes_vmalert_context_in_incident_report(self) -> None:
        """Test that build_run_payload includes vmalert context in incident report."""
        index = sample_ui_index()
        run_entry = cast(dict[str, object], index["run"])
        run_entry["vmalert_sources"] = {
            "sources": [
                {
                    "source_id": "test-vmalert",
                    "endpoint": "http://vmalert:8880",
                    "namespace": "victoria-metrics",
                    "name": "vmalert",
                    "origin": "service-heuristic",
                    "state": "discovered",
                    "discovered_at": "2026-01-01T00:00:00Z",
                    "verified_at": None,
                    "last_check": None,
                    "last_error": None,
                    "verified_version": None,
                    "confidence_hints": [],
                    "merged_provenances": ["service-heuristic"],
                    "display_provenance": "Service Heuristic",
                    "is_manual": False,
                    "is_tracking": False,
                    "can_disable": False,
                    "can_promote": True,
                    "display_origin": "Service Heuristic",
                    "display_state": "Discovered",
                    "provenance_summary": "-",
                    "cluster_label": "cluster-a",
                    "manual_source_mode": None,
                    "canonicalEntityId": None,
                    "cluster_uid": None,
                    "object_uid": None,
                }
            ],
            "total_count": 1,
            "source_count": 1,
            "discovered_count": 1,
            "discovered_but_unverified_count": 0,
            "auto_tracked_count": 0,
            "manual_count": 0,
            "discovery_timestamp": "2026-01-01T00:00:00Z",
            "cluster_context": "cluster-a",
        }
        context = build_ui_context(index)
        run_payload = build_run_payload(context)
        # Check incident report in run payload
        self.assertIn("incidentReport", run_payload)
        incident_report = run_payload["incidentReport"]
        self.assertIsNotNone(incident_report)
        assert incident_report is not None
        # Verify vmalert context is threaded through
        self.assertIn("vmalertDiscoveryContext", incident_report)
        self.assertIsNotNone(incident_report["vmalertDiscoveryContext"])
