"""Runtime verifier tests for the portable validation attestation.

ACT-K9B-HULK-PROMOTION-FINAL-LOCAL-ACCEPTANCE01-CORRECTION05:

The verifier (:mod:`scripts.factory.gate_summary_validation_attestation`)
MUST accept portable repository-relative ``validated_path`` values
and reject absolute / traversal / outside-repo paths. The committed
attestation file is regenerated by the canonical producer, so its
contents MUST be identical on every runner (macOS developer
workstation, Linux CI runner).
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from scripts.factory.gate_summary_validation_attestation import (  # noqa: E402
    _AttestationError,
    _reject_forbidden_absolute,
    resolve_validated_path,
    verify_validation_attestation,
)

# ---------------------------------------------------------------------------
# Bounded path-prefix rejection
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "prefix",
    ["/Users/", "/home/runner/", "/home/circleci/", "/root/", "C:\\", "D:\\", "/private/"],
)
def test_forbidden_absolute_prefixes_are_rejected(prefix: str) -> None:
    with pytest.raises(_AttestationError) as exc:
        _reject_forbidden_absolute(prefix + "some/where")
    assert "forbidden absolute prefix" in str(exc.value) or "absolute path" in str(exc.value)


def test_bare_posix_absolute_path_is_rejected() -> None:
    """A bare absolute path not matching the explicit prefix list is
    also rejected -- the contract is "repository-relative only"."""
    with pytest.raises(_AttestationError) as exc:
        _reject_forbidden_absolute("/etc/passwd")
    assert "absolute path" in str(exc.value)


def test_empty_or_invalid_path_is_rejected() -> None:
    for bad in ("", None, 123):
        with pytest.raises(_AttestationError):
            _reject_forbidden_absolute(bad)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# resolve_validated_path path safety
# ---------------------------------------------------------------------------


def test_portable_relative_path_is_accepted(tmp_path: Path) -> None:
    """The canonical ``.factory/gate-summary.json`` resolves inside
    ``repo_root``."""
    factory = tmp_path / ".factory"
    factory.mkdir()
    target = factory / "gate-summary.json"
    target.write_text("{}", encoding="utf-8")
    resolved = resolve_validated_path(
        repo_root=tmp_path, validated_path=".factory/gate-summary.json"
    )
    assert resolved == target.resolve()


def test_macos_absolute_path_is_rejected(tmp_path: Path) -> None:
    with pytest.raises(_AttestationError):
        resolve_validated_path(
            repo_root=tmp_path,
            validated_path="/Users/dev/proj/.factory/gate-summary.json",
        )


def test_linux_runner_absolute_path_is_rejected(tmp_path: Path) -> None:
    with pytest.raises(_AttestationError):
        resolve_validated_path(
            repo_root=tmp_path,
            validated_path="/home/runner/work/.factory/gate-summary.json",
        )


def test_dotdot_path_traversal_is_rejected(tmp_path: Path) -> None:
    with pytest.raises(_AttestationError) as exc:
        resolve_validated_path(
            repo_root=tmp_path,
            validated_path="../escape/.factory/gate-summary.json",
        )
    assert ".." in str(exc.value) or "traversal" in str(exc.value)


def test_traversal_escapes_repo_root_is_rejected(tmp_path: Path) -> None:
    """Even a path that resolves to a sibling tree is rejected if it
    escapes ``repo_root``."""
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    outside = tmp_path / "outside"
    outside.mkdir()
    outside_file = outside / "gate-summary.json"
    outside_file.write_text("{}", encoding="utf-8")
    with pytest.raises(_AttestationError) as exc:
        resolve_validated_path(
            repo_root=repo_root,
            validated_path=(
                f"../{outside.name}/gate-summary.json"
            ),
        )
    assert "outside repo_root" in str(exc.value) or ".." in str(exc.value)


# ---------------------------------------------------------------------------
# End-to-end attestation verification
# ---------------------------------------------------------------------------


def _write_attestation(
    *,
    attestation_path: Path,
    validated_path: str,
    validated_sha256: str,
    parser_identity: str = "scripts/factory/parse_gate_summary.py",
    decode_status: str = "pass",
    acceptance_status: str = "pass",
) -> None:
    payload = {
        "schema_version": 1,
        "validated_path": validated_path,
        "validated_sha256": validated_sha256,
        "validated_at": "2026-07-30T00:00:00+00:00",
        "parser_identity": parser_identity,
        "parser_command": "<test>",
        "parser_exit_code": 0,
        "parser_duration_ms": 0,
        "decode_status": decode_status,
        "acceptance_status": acceptance_status,
        "diagnostics": {},
    }
    attestation_path.write_text(
        json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )


def _build_repo_with_factory_artifact(tmp_path: Path) -> tuple[Path, Path, str]:
    factory = tmp_path / ".factory"
    factory.mkdir()
    artifact = factory / "gate-summary.json"
    artifact.write_text("{\"schema_version\": 1}", encoding="utf-8")
    sha = hashlib.sha256(artifact.read_bytes()).hexdigest()
    return artifact, tmp_path, sha


def test_verify_validation_attestation_accepts_portable_relative_path(tmp_path: Path) -> None:
    """The canonical committed attestation MUST verify end-to-end with
    no SHA mismatch and no path rejection."""
    artifact, repo_root, sha = _build_repo_with_factory_artifact(tmp_path)
    attestation_path = artifact.parent / "gate-summary-validation.json"
    _write_attestation(
        attestation_path=attestation_path,
        validated_path=".factory/gate-summary.json",
        validated_sha256=sha,
    )
    result = verify_validation_attestation(
        repo_root=repo_root, attestation_path=attestation_path
    )
    assert result.sha_matches is True
    assert result.decode_status == "pass"
    assert result.acceptance_status == "pass"
    assert result.parser_identity == "scripts/factory/parse_gate_summary.py"
    assert result.portable_validated_path == ".factory/gate-summary.json"
    assert result.validated_path == artifact.resolve()


def test_verify_validation_attestation_rejects_sha_mismatch(tmp_path: Path) -> None:
    """A mutation of the validated artifact between attestation write
    and verifier invocation MUST surface as a SHA mismatch."""
    artifact, repo_root, sha = _build_repo_with_factory_artifact(tmp_path)
    attestation_path = artifact.parent / "gate-summary-validation.json"
    # Mutate the artifact AFTER writing the attestation so the SHA
    # recorded in the attestation no longer matches the on-disk bytes.
    artifact.write_text("{\"mutated\": true}", encoding="utf-8")
    _write_attestation(
        attestation_path=attestation_path,
        validated_path=".factory/gate-summary.json",
        validated_sha256=sha,
    )
    with pytest.raises(_AttestationError) as exc:
        verify_validation_attestation(
            repo_root=repo_root, attestation_path=attestation_path
        )
    assert "SHA mismatch" in str(exc.value)


def test_verify_validation_attestation_rejects_absolute_path(tmp_path: Path) -> None:
    artifact, repo_root, sha = _build_repo_with_factory_artifact(tmp_path)
    attestation_path = artifact.parent / "gate-summary-validation.json"
    _write_attestation(
        attestation_path=attestation_path,
        validated_path="/Users/dev/proj/.factory/gate-summary.json",
        validated_sha256=sha,
    )
    with pytest.raises(_AttestationError) as exc:
        verify_validation_attestation(
            repo_root=repo_root, attestation_path=attestation_path
        )
    assert "portable" in str(exc.value).lower() or "absolute" in str(exc.value).lower()


def test_verify_validation_attestation_rejects_traversal(tmp_path: Path) -> None:
    artifact, repo_root, sha = _build_repo_with_factory_artifact(tmp_path)
    attestation_path = artifact.parent / "gate-summary-validation.json"
    _write_attestation(
        attestation_path=attestation_path,
        validated_path="../escape/.factory/gate-summary.json",
        validated_sha256=sha,
    )
    with pytest.raises(_AttestationError):
        verify_validation_attestation(
            repo_root=repo_root, attestation_path=attestation_path
        )


def test_verify_validation_attestation_rejects_missing_attestation(tmp_path: Path) -> None:
    artifact, repo_root, _ = _build_repo_with_factory_artifact(tmp_path)
    # No attestation file written at all.
    attestation_path = artifact.parent / "gate-summary-validation.json"
    with pytest.raises(_AttestationError) as exc:
        verify_validation_attestation(
            repo_root=repo_root, attestation_path=attestation_path
        )
    assert "missing" in str(exc.value)


def test_verify_validation_attestation_rejects_bad_status_enum(tmp_path: Path) -> None:
    artifact, repo_root, sha = _build_repo_with_factory_artifact(tmp_path)
    attestation_path = artifact.parent / "gate-summary-validation.json"
    _write_attestation(
        attestation_path=attestation_path,
        validated_path=".factory/gate-summary.json",
        validated_sha256=sha,
        decode_status="maybe",
    )
    with pytest.raises(_AttestationError) as exc:
        verify_validation_attestation(
            repo_root=repo_root, attestation_path=attestation_path
        )
    assert "decode_status" in str(exc.value)


def test_verify_validation_attestation_rejects_nonhex_sha(tmp_path: Path) -> None:
    artifact, repo_root, _ = _build_repo_with_factory_artifact(tmp_path)
    attestation_path = artifact.parent / "gate-summary-validation.json"
    _write_attestation(
        attestation_path=attestation_path,
        validated_path=".factory/gate-summary.json",
        validated_sha256="not-hex",
    )
    with pytest.raises(_AttestationError) as exc:
        verify_validation_attestation(
            repo_root=repo_root, attestation_path=attestation_path
        )
    assert "validated_sha256" in str(exc.value)
